# ~/.dbt/profiles.yml
# Optimized for Story S031-02: Year Processing Optimization
# Configuration specifically tuned for analytical workloads and batch processing

planwise_navigator:
  target: optimized # Optimized target for S031-02 performance improvements
  outputs:
    optimized:
      type: duckdb
      path: "/Users/nicholasamaral/planwise_navigator/dbt/simulation.duckdb"
      schema: main

      # Optimized threading for batch execution (3-4 threads per S031-02 requirements)
      threads: 4 # Optimized for batch processing efficiency

      extensions:
        - parquet
        - httpfs
        - fts # Full-text search for debugging
        - json # JSON functions for metadata

      settings:
        # S031-02 Memory Optimization: 1-2GB per model allocation
        memory_limit: '4GB' # Conservative limit to stay under 4GB peak usage target

        # Analytical workload optimizations
        # enable_optimization_statistics: true # Not available in current DuckDB version
        # enable_vectorized_execution: true # Not available in current DuckDB version
        enable_progress_bar: true # Progress tracking for long-running queries

        # Batch processing optimizations
        # force_parallelism: true # Not available in current DuckDB version
        # force_index_join: false # Not available in current DuckDB version

        # Memory and performance tuning for workforce analytics
        # checkpoint_wal_size: 134217728 # Not available in current DuckDB version
        max_memory: '4GB' # Hard memory limit

        # Columnar storage optimizations for workforce data
        default_order: 'ASC' # Optimize for time-series workforce data

        # Connection and timeout settings for batch operations
        # lock_timeout: 300000 # Not available in current DuckDB version
        # query_timeout: 1800000 # Not available in current DuckDB version

    # Legacy target for compatibility
    dev_m4:
      type: duckdb
      path: "/Users/nicholasamaral/planwise_navigator/dbt/simulation.duckdb"
      schema: main
      threads: 10
      extensions:
        - parquet
        - httpfs
      settings:
        memory_limit: '8GB'
