# ~/.dbt/profiles.yml
# Optimized for Epic E067: Multi-Threading Navigator Orchestrator
# Configuration enhanced for multi-threaded execution with Navigator Orchestrator

planwise_navigator:
  target: dev # E067-ready target for multi-threading support
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DATABASE_PATH', 'simulation.duckdb') }}"
      schema: main

      # E067 Dynamic Threading: Navigator Orchestrator overrides this via --threads parameter
      # This serves as fallback for direct dbt execution (E067 supports 1-16 threads)
      threads: 4 # Baseline thread count - dynamically overridden by E067

      extensions:

      settings:
        # S031-02 Memory Optimization: 1-2GB per model allocation
        memory_limit: '4GB' # Conservative limit to stay under 4GB peak usage target

        # Analytical workload optimizations
        # enable_optimization_statistics: true # Not available in current DuckDB version
        # enable_vectorized_execution: true # Not available in current DuckDB version
        enable_progress_bar: true # Progress tracking for long-running queries

        # Batch processing optimizations
        # force_parallelism: true # Not available in current DuckDB version
        # force_index_join: false # Not available in current DuckDB version

        # Memory and performance tuning for workforce analytics
        # checkpoint_wal_size: 134217728 # Not available in current DuckDB version
        max_memory: '4GB' # Hard memory limit

        # Columnar storage optimizations for workforce data
        default_order: 'ASC' # Optimize for time-series workforce data

        # Connection and timeout settings for batch operations
        # lock_timeout: 300000 # Not available in current DuckDB version
        # query_timeout: 1800000 # Not available in current DuckDB version

    # Legacy target for compatibility
    dev_m4:
      type: duckdb
      path: "{{ env_var('DATABASE_PATH', 'simulation.duckdb') }}"
      schema: main
      threads: 10
      extensions:
      settings:
        memory_limit: '8GB'
