"""
Eligibility Event Generator (Feature 086)

Thin wrapper around the int_eligibility_events dbt model.
Delegates event generation to SQL while providing the EventGenerator
interface for the abstraction layer.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, List

from planalign_orchestrator.generators.base import (
    EventContext,
    EventGenerator,
    ValidationResult,
)
from planalign_orchestrator.generators.registry import EventRegistry

from config.constants import EVENT_ELIGIBILITY

if TYPE_CHECKING:
    from config.events import SimulationEvent

logger = logging.getLogger(__name__)


@EventRegistry.register(EVENT_ELIGIBILITY)
class EligibilityEventGenerator(EventGenerator):
    """
    Generate DC plan eligibility events.

    Delegates to int_eligibility_events dbt model which:
    - Reads from int_plan_eligibility_determination (age + waiting period gates)
    - Emits one event per employee per simulation on first eligibility transition
    - Uses self-reference anti-join for multi-year deduplication

    Execution Order: 25 (after hire=20, before promotion=30 and enrollment=50)
    """

    event_type = EVENT_ELIGIBILITY
    execution_order = 25
    requires_hazard = False
    supports_sql = True

    dbt_models = [
        "int_plan_eligibility_determination",
        "int_eligibility_events",
    ]

    def generate_events(self, context: EventContext) -> List["SimulationEvent"]:
        logger.debug(
            f"eligibility: events generated by dbt model "
            f"int_eligibility_events for year {context.simulation_year}"
        )
        return []

    def validate_event(self, event: "SimulationEvent") -> ValidationResult:
        errors: List[str] = []

        payload = event.payload
        if payload.event_type != EVENT_ELIGIBILITY:
            errors.append(
                f"Expected event_type '{EVENT_ELIGIBILITY}', got '{payload.event_type}'"
            )
            return ValidationResult(is_valid=False, errors=errors)

        if not hasattr(payload, "eligibility_date") or payload.eligibility_date is None:
            errors.append("eligibility_date is required")

        return ValidationResult(is_valid=len(errors) == 0, errors=errors)

    def get_dbt_models(self) -> List[str]:
        return self.dbt_models
