"""
Promotion Event Generator Wrapper (T024)

Thin wrapper around existing dbt promotion event models.
Delegates event generation to SQL models while providing
the EventGenerator interface for the abstraction layer.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, List

from planalign_orchestrator.generators.base import (
    EventContext,
    EventGenerator,
    ValidationResult,
    HazardBasedEventGeneratorMixin,
)
from planalign_orchestrator.generators.registry import EventRegistry

if TYPE_CHECKING:
    from config.events import SimulationEvent

logger = logging.getLogger(__name__)


@EventRegistry.register("promotion")
class PromotionEventGenerator(HazardBasedEventGeneratorMixin, EventGenerator):
    """
    Generate promotion events for workforce simulation.

    This wrapper delegates to existing dbt models:
    - int_hazard_promotion: Hazard probability calculation
    - int_promotion_events: Final promotion event generation

    Promotions use hazard probability tables based on age, tenure, and
    current job level to determine advancement eligibility.

    Execution Order: 30 (after hires, before merit)
    """

    event_type = "promotion"
    execution_order = 30
    requires_hazard = True
    supports_sql = True

    # dbt model references
    dbt_models = ["int_hazard_promotion", "int_promotion_events"]
    hazard_table_name = "config_promotion_hazard"

    def generate_events(self, context: EventContext) -> List["SimulationEvent"]:
        """
        Generate promotion events for the simulation year.

        Delegates to dbt models which handle:
        - Hazard-based promotion selection
        - Compensation adjustment calculation
        - Job level advancement

        Args:
            context: Runtime context with year, config, database access

        Returns:
            Empty list (events generated by dbt)
        """
        logger.debug(
            f"promotion: events generated by dbt models "
            f"{self.dbt_models} for year {context.simulation_year}"
        )
        return []

    def validate_event(self, event: "SimulationEvent") -> ValidationResult:
        """
        Validate a promotion event.

        Validates:
        - Event type is "promotion"
        - new_job_level is valid (1-10)
        - new_annual_compensation is positive
        - effective_date is present

        Args:
            event: The promotion event to validate

        Returns:
            ValidationResult with is_valid flag and any errors
        """
        errors: List[str] = []
        warnings: List[str] = []

        # Check event type
        payload = event.payload
        if payload.event_type != "promotion":
            errors.append(f"Expected event_type 'promotion', got '{payload.event_type}'")
            return ValidationResult(is_valid=False, errors=errors)

        # Validate new_job_level
        if hasattr(payload, "new_job_level"):
            if payload.new_job_level < 1 or payload.new_job_level > 10:
                errors.append(
                    f"new_job_level must be between 1 and 10, got {payload.new_job_level}"
                )
        else:
            errors.append("new_job_level is required")

        # Validate new_annual_compensation
        if hasattr(payload, "new_annual_compensation"):
            if payload.new_annual_compensation <= 0:
                errors.append(
                    f"new_annual_compensation must be positive, "
                    f"got {payload.new_annual_compensation}"
                )
        else:
            errors.append("new_annual_compensation is required")

        # Validate effective_date
        if not hasattr(payload, "effective_date") or payload.effective_date is None:
            errors.append("effective_date is required")

        return ValidationResult(
            is_valid=len(errors) == 0, errors=errors, warnings=warnings
        )

    def get_dbt_models(self) -> List[str]:
        """Get list of dbt models for this generator."""
        return self.dbt_models
