version: 2

sources:
  - name: snapshots
    description: "dbt snapshots schema containing historical workforce state"
    schema: main
    tables:
      - name: scd_workforce_state
        description: "Slowly changing dimension table capturing workforce state at the end of each simulation year"
        columns:
          - name: employee_id
            description: "Unique identifier for each employee"
          - name: employee_ssn
            description: "Employee social security number"
          - name: employee_birth_date
            description: "Employee birth date"
          - name: employee_hire_date
            description: "Employee hire date"
          - name: employee_gross_compensation
            description: "Employee gross compensation"
          - name: current_age
            description: "Employee age at snapshot time"
          - name: current_tenure
            description: "Employee tenure at snapshot time"
          - name: level_id
            description: "Job level ID"
          - name: termination_date
            description: "Termination date if applicable"
          - name: employment_status
            description: "Employment status (active/terminated)"
          - name: simulation_year
            description: "Simulation year this snapshot represents"
          - name: snapshot_created_at
            description: "Timestamp when snapshot was taken"
          - name: dbt_scd_id
            description: "dbt snapshot ID"
          - name: dbt_updated_at
            description: "dbt snapshot update timestamp"
          - name: dbt_valid_from
            description: "dbt snapshot valid from timestamp"
          - name: dbt_valid_to
            description: "dbt snapshot valid to timestamp"

  - name: raw_data_parquet
    description: "Raw data sources optimized for DuckDB performance using Parquet format"
    tables:
      - name: comp_levers_parquet
        description: "Compensation parameters in Parquet format for enhanced I/O performance"
        external:
          location: "data/parquet/comp_levers.parquet"
          file_format: parquet
        columns:
          - name: scenario_id
            data_type: varchar
            description: "Scenario identifier"
          - name: fiscal_year
            data_type: integer
            description: "Fiscal year for the parameter"
          - name: job_level
            data_type: integer
            description: "Job level ID"
          - name: event_type
            data_type: varchar
            description: "Type of event (raise, promotion, etc.)"
          - name: parameter_name
            data_type: varchar
            description: "Name of the compensation parameter"
          - name: parameter_value
            data_type: decimal(10,4)
            description: "Value of the parameter"
          - name: is_locked
            data_type: boolean
            description: "Whether parameter is locked for editing"
          - name: created_at
            data_type: date
            description: "Parameter creation date"
          - name: created_by
            data_type: varchar
            description: "User who created the parameter"

      - name: comp_targets_parquet
        description: "Compensation targets in Parquet format"
        external:
          location: "data/parquet/comp_targets.parquet"
          file_format: parquet
        columns:
          - name: scenario_id
            data_type: varchar
          - name: job_level
            data_type: integer
          - name: target_salary
            data_type: decimal(10,2)
          - name: target_bonus_pct
            data_type: decimal(5,4)

      - name: default_deferral_rates_parquet
        description: "Default employee deferral rates in Parquet format"
        external:
          location: "data/parquet/default_deferral_rates.parquet"
          file_format: parquet
        columns:
          - name: job_level
            data_type: integer
          - name: age_group
            data_type: varchar
          - name: default_deferral_rate
            data_type: decimal(5,4)

      - name: config_job_levels_parquet
        description: "Job level configuration in Parquet format"
        external:
          location: "data/parquet/config_job_levels.parquet"
          file_format: parquet
        columns:
          - name: level_id
            data_type: integer
          - name: level_name
            data_type: varchar
          - name: min_salary
            data_type: decimal(10,2)
          - name: max_salary
            data_type: decimal(10,2)

  - name: polars_events
    description: "Event data generated by Polars bulk event factory (Epic E068G) - High-performance alternative to SQL event generation"
    tables:
      - name: fct_yearly_events_polars
        description: "All yearly events from Polars bulk factory - partitioned by simulation_year for optimal query performance"
        external:
          location: "{{ var('polars_events_path', 'data/parquet/polars_events') }}/simulation_year=*/*.parquet"
          file_format: parquet
        columns:
          - name: event_id
            data_type: varchar
            description: "Unique identifier for each event, deterministically generated from employee + year + event type"
          - name: scenario_id
            data_type: varchar
            description: "Scenario identifier for multi-scenario planning"
          - name: plan_design_id
            data_type: varchar
            description: "Plan design identifier for plan-specific configurations"
          - name: employee_id
            data_type: varchar
            description: "Unique employee identifier"
          - name: employee_ssn
            data_type: varchar
            description: "Employee social security number"
          - name: event_type
            data_type: varchar
            description: "Type of event (hire, termination, promotion, raise, enrollment, enrollment_change, deferral_escalation)"
          - name: simulation_year
            data_type: integer
            description: "Simulation year when event occurs"
          - name: effective_date
            data_type: date
            description: "Date when event becomes effective"
          - name: event_details
            data_type: varchar
            description: "Human-readable description of the event"
          - name: compensation_amount
            data_type: decimal(10,2)
            description: "Compensation amount associated with the event (new salary after raise/promotion)"
          - name: previous_compensation
            data_type: decimal(10,2)
            description: "Previous compensation amount before the event"
          - name: employee_deferral_rate
            data_type: decimal(5,4)
            description: "Employee deferral rate after the event"
          - name: prev_employee_deferral_rate
            data_type: decimal(5,4)
            description: "Previous employee deferral rate before the event"
          - name: employee_age
            data_type: integer
            description: "Employee age at time of event"
          - name: employee_tenure
            data_type: decimal(5,2)
            description: "Employee tenure in years at time of event"
          - name: level_id
            data_type: integer
            description: "Job level identifier"
          - name: age_band
            data_type: varchar
            description: "Age band classification for analysis"
          - name: tenure_band
            data_type: varchar
            description: "Tenure band classification for analysis"
          - name: event_probability
            data_type: decimal(8,6)
            description: "Probability used for event generation (for audit and analysis)"
          - name: event_category
            data_type: varchar
            description: "High-level category of event for analysis and reporting"
          - name: event_sequence
            data_type: integer
            description: "Sequence number for ordering events within employee/year"
          - name: created_at
            data_type: timestamp
            description: "Timestamp when event record was created"
          - name: parameter_scenario_id
            data_type: varchar
            description: "Parameter scenario used for event generation"
          - name: parameter_source
            data_type: varchar
            description: "Source of parameters (polars_factory for E068G events)"
          - name: data_quality_flag
            data_type: varchar
            description: "Data quality validation flag (VALID/INVALID_*)"
