version: 2

sources:
  - name: snapshots
    description: >
      Snapshot tables that capture historical state of workforce data.
      Used to break circular dependencies in multi-year simulations.
    database: main
    schema: main
    tables:
      - name: scd_workforce_state
        description: >
          Workforce state snapshot capturing end-of-simulation-year data.
          This table is materialized by the scd_workforce_state snapshot
          and provides historical workforce state for subsequent year simulations.
        columns:
          - name: employee_id
            description: Unique identifier for each employee
          - name: simulation_year
            description: The simulation year this snapshot represents
          - name: employment_status
            description: Employment status (active/terminated)
          - name: dbt_valid_from
            description: Timestamp when this record became valid (snapshot metadata)
          - name: dbt_valid_to
            description: Timestamp when this record became invalid, NULL for current (snapshot metadata)
