"""Apply a fitted parameter pack to a simulation run.

``planalign simulate --params <pack>`` has to change two things: the seed CSVs
dbt loads, and the config values the orchestrator exports as dbt vars. Neither
may mutate the repository — a pack is evidence, not a commit — so applying one
builds an **overlay dbt project** whose ``seeds/`` is a private copy with the
pack's CSVs swapped in, and writes an **effective config** that deep-merges the
pack's fragment over the base config.

Everything downstream of config loading is untouched: the orchestrator receives
an ordinary config path and an ordinary ``--dbt-project-dir``, both of which it
already supports.
"""

from __future__ import annotations

import logging
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import yaml

from planalign_fit.pack import (
    PackError,
    PackManifest,
    ParameterPack,
    deep_merge,
    load_pack,
    verify_pack,
)

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
DBT_ROOT = REPO_ROOT / "dbt"
DEFAULT_WORKDIR = REPO_ROOT / "var" / "param_packs"

# Directories the overlay links back to the real project rather than copying:
# only seeds differ under a parameter pack.
LINKED_ENTRIES = (
    "analyses",
    "macros",
    "models",
    "snapshots",
    "tests",
    "packages.yml",
    "package-lock.yml",
    "dbt_packages",
)

CONFIG_FILENAME = "effective_config.yaml"
PROJECT_DIRNAME = "dbt_project"
SEEDS_DIRNAME = "seeds"


@dataclass(frozen=True)
class AppliedPack:
    """The materialized run inputs for one parameter pack."""

    manifest: PackManifest
    config_path: Path
    dbt_project_dir: Path
    workdir: Path
    fingerprint_verified: bool


def provenance_block(manifest: PackManifest) -> dict[str, Any]:
    """The ``param_pack`` block stamped into the effective config.

    ``SimulationConfig`` keeps unknown top-level keys, and ``to_dbt_vars``
    ignores them, so this rides along without perturbing the config
    fingerprint — it is provenance, not a result-affecting input.
    """
    return {
        "pack_id": manifest.pack_id,
        "fingerprint": manifest.fingerprint,
        "fit_date": manifest.fit_date,
        "source_digest": manifest.source_digest,
        "snapshot_years": list(manifest.snapshot_years),
        # Whether the promotion hazard behind this run was fitted from the
        # client's history or is a retained default (#511). Rides the same
        # mechanism as the rest of the block: `to_dbt_vars` ignores unknown
        # top-level keys, so it reaches `run_metadata` without perturbing the
        # config fingerprint.
        "promotion_basis": manifest.promotion_basis,
    }


def apply_pack(
    pack_dir: Path | str,
    base_config: Path | str,
    *,
    workdir: Optional[Path] = None,
    dbt_root: Optional[Path] = None,
) -> AppliedPack:
    """Materialize the config and dbt project a pack-backed run needs."""
    pack = load_pack(pack_dir)
    verified = verify_pack(pack)
    if not verified:
        logger.warning(
            "Parameter pack %s no longer matches its recorded fingerprint — its "
            "files were edited after fitting. The run proceeds with the files as "
            "they are on disk; treat the pack's provenance as unreliable.",
            pack.manifest.pack_id,
        )

    root = Path(workdir) if workdir else DEFAULT_WORKDIR / pack.manifest.pack_id
    root.mkdir(parents=True, exist_ok=True)

    config_path = _write_effective_config(pack, Path(base_config), root)
    project_dir = _build_overlay_project(pack, root, dbt_root or DBT_ROOT)

    return AppliedPack(
        manifest=pack.manifest,
        config_path=config_path,
        dbt_project_dir=project_dir,
        workdir=root,
        fingerprint_verified=verified,
    )


def _write_effective_config(
    pack: ParameterPack, base_config: Path, workdir: Path
) -> Path:
    if not base_config.is_file():
        raise PackError(f"Base config not found: {base_config}")
    with base_config.open("r", encoding="utf-8") as handle:
        base = yaml.safe_load(handle) or {}

    effective = deep_merge(base, pack.config_fragment)
    effective["param_pack"] = provenance_block(pack.manifest)

    destination = workdir / CONFIG_FILENAME
    with destination.open("w", encoding="utf-8") as handle:
        handle.write(
            f"# Effective config: {base_config} + parameter pack "
            f"{pack.manifest.pack_id}\n"
            "# Generated by `planalign simulate --params`. Do not edit — rerun "
            "the command instead.\n"
        )
        yaml.safe_dump(effective, handle, default_flow_style=False, sort_keys=False)
    return destination


def _build_overlay_project(pack: ParameterPack, workdir: Path, dbt_root: Path) -> Path:
    """A dbt project identical to the real one except for its seeds."""
    overlay = workdir / PROJECT_DIRNAME
    overlay.mkdir(parents=True, exist_ok=True)
    shutil.copy2(dbt_root / "dbt_project.yml", overlay / "dbt_project.yml")
    for entry in LINKED_ENTRIES:
        _link(dbt_root / entry, overlay / entry)

    seeds = overlay / SEEDS_DIRNAME
    if seeds.is_symlink():
        seeds.unlink()
    if seeds.exists():
        shutil.rmtree(seeds)
    shutil.copytree(dbt_root / SEEDS_DIRNAME, seeds)

    for name, text in pack.seed_files.items():
        target = seeds / name
        if not target.exists():
            raise PackError(
                f"Pack seed '{name}' has no counterpart in {dbt_root / SEEDS_DIRNAME}. "
                "The pack was fitted against a different seed set."
            )
        target.write_text(text, encoding="utf-8")

    return overlay


def _link(source: Path, destination: Path) -> None:
    """Point ``destination`` at ``source`` so the overlay never copies models."""
    if not source.exists():
        return
    if destination.is_symlink():
        if destination.resolve() == source.resolve():
            return
        destination.unlink()
    elif destination.is_file():
        destination.unlink()
    elif destination.exists():
        shutil.rmtree(destination)
    destination.symlink_to(source, target_is_directory=source.is_dir())
