version: 2

models:
  - name: int_cold_start_detection
    description: >
      Cold start detection logic with table existence check.
      Determines if this is a cold start or continuation of existing simulation.
      Uses table existence check to safely handle empty databases.
    config:
      tags: ["foundation", "critical"]
    columns:
      - name: is_cold_start
        description: Boolean flag indicating if this is a cold start scenario
        data_tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: last_completed_year
        description: The last completed simulation year (0 if cold start)
        data_tests:
          - not_null

  - name: int_simulation_run_log
    description: >
      Simulation run log for tracking completed years.
      Only inserts when a simulation year completes successfully.
    config:
      tags: ["monitoring", "incremental"]
    columns:
      - name: simulation_year
        description: The completed simulation year
        data_tests:
          - unique
          - not_null
      - name: completion_timestamp
        description: When the simulation year completed
        data_tests:
          - not_null
      - name: run_status
        description: Status of the simulation run
        data_tests:
          - not_null
          - accepted_values:
              values: ['COMPLETED', 'FAILED']
      - name: total_employees_processed
        description: Total number of employees processed in this year
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0

  - name: int_year_snapshot_preparation
    description: >
      Year snapshot preparation enhancement with validation hooks.
      Prepares workforce data for the current simulation year with validation.
    config:
      tags: ["foundation", "critical"]
    columns:
      - name: employee_id
        description: Unique identifier for each employee
        data_tests:
          - unique
          - not_null
      - name: simulation_year
        description: The simulation year this snapshot represents
        data_tests:
          - not_null
      - name: employment_status
        description: Employment status (active for snapshot preparation)
        data_tests:
          - not_null
          - accepted_values:
              values: ['active']
      - name: is_cold_start
        description: Boolean flag indicating if this is a cold start scenario
        data_tests:
          - not_null
      - name: baseline_active_count
        description: Number of active employees in baseline
        data_tests:
          - not_null
      - name: baseline_total_count
        description: Total number of employees in baseline
        data_tests:
          - not_null

  - name: int_baseline_workforce
    description: >
      Baseline workforce for simulation start, driven by simulation parameters.
      This model provides the initial state of the workforce for multi-year simulations.

      Key features:
      - Calculates age and tenure based on simulation_effective_date
      - Assigns level_id based on compensation bands
      - Creates age and tenure bands for analysis
      - Only includes active employees (no termination date)
    config:
      tags: ["foundation", "critical"]

    columns:
      - name: employee_id
        description: Unique identifier for each employee
        data_tests:
          - unique
          - not_null

      - name: employee_ssn
        description: Employee social security number (masked/encrypted in production)
        data_tests:
          - not_null

      - name: employee_birth_date
        description: Employee birth date
        data_tests:
          - not_null

      - name: employee_hire_date
        description: Employee hire date
        data_tests:
          - not_null

      - name: current_compensation
        description: Employee current gross compensation
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false

      - name: current_age
        description: Employee age as of simulation_effective_date
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 16
              max_value: 100

      - name: current_tenure
        description: Employee tenure in years as of simulation_effective_date
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 60

      - name: level_id
        description: Job level ID based on compensation bands
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_config_job_levels')
              field: level_id

      - name: age_band
        description: Age band for analysis (< 25, 25-34, 35-44, 45-54, 55-64, 65+)
        data_tests:
          - not_null
          - accepted_values:
              values: ['< 25', '25-34', '35-44', '45-54', '55-64', '65+']

      - name: tenure_band
        description: Tenure band for analysis (< 2, 2-4, 5-9, 10-19, 20+)
        data_tests:
          - not_null
          - accepted_values:
              values: ['< 2', '2-4', '5-9', '10-19', '20+']

      - name: employment_status
        description: Employment status (always 'active' for baseline)
        data_tests:
          - not_null
          - accepted_values:
              values: ['active']

      - name: termination_date
        description: Termination date (NULL for baseline workforce)

      - name: termination_reason
        description: Termination reason (NULL for baseline workforce)

      - name: simulation_year
        description: The simulation year this baseline represents
        data_tests:
          - not_null

      - name: snapshot_created_at
        description: Timestamp when this snapshot was created
        data_tests:
          - not_null

      - name: is_from_census
        description: Boolean flag indicating if this employee originated from census data
        data_tests:
          - not_null

      - name: is_cold_start
        description: Boolean flag indicating if this is a cold start scenario
        data_tests:
          - not_null

      - name: last_completed_year
        description: The last completed simulation year before this baseline
        data_tests:
          - not_null

  - name: int_workforce_previous_year
    description: >
      Enhanced previous year workforce model with fallback handling.
      Gracefully handles missing prior year data without errors.
    config:
      tags: ["foundation", "critical"]
    columns:
      - name: employee_id
        description: Unique identifier for each employee
        data_tests:
          - unique
          - not_null
      - name: employment_status
        description: Employment status (active/terminated)
        data_tests:
          - not_null
      - name: simulation_year
        description: Simulation year this workforce represents
        data_tests:
          - not_null
      - name: is_from_census
        description: Boolean flag indicating if this employee originated from census data
        data_tests:
          - not_null
      - name: is_cold_start
        description: Boolean flag indicating if this is a cold start scenario
        data_tests:
          - not_null
      - name: active_employees
        description: Total number of active employees in this workforce
        data_tests:
          - not_null
      - name: total_employees
        description: Total number of employees in this workforce
        data_tests:
          - not_null

  - name: int_termination_events
    description: >
      Hazard-based termination events for workforce simulation.
      Uses demographic-aware probability models to select employees for termination.

      Key features:
      - Hazard-based selection using termination probability by age/tenure/level
      - Deterministic randomization with employee_id hash for reproducibility
      - Demographically-aware modeling (higher turnover for new hires)
      - Consistent with promotion event selection pattern
    config:
      tags: ["event_sourcing"]

    # data_tests will be validated at the column level

    columns:
      - name: employee_id
        description: Unique identifier for terminated employee
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('int_workforce_previous_year')
              field: employee_id

      - name: event_type
        description: Type of event (always 'termination')
        data_tests:
          - not_null
          - accepted_values:
              values: ['termination']

      - name: simulation_year
        description: Year when termination occurs
        data_tests:
          - not_null

      - name: effective_date
        description: Specific date when termination is effective
        data_tests:
          - not_null

      - name: termination_reason
        description: Reason for termination
        data_tests:
          - not_null
          - accepted_values:
              values: ['hazard_termination', 'gap_filling_termination']

      - name: termination_rate
        description: Probability rate used for this employee's termination
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true

      - name: random_value
        description: Random value used for probability comparison
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true

      - name: age_band
        description: Age band of terminated employee
        data_tests:
          - not_null
          - accepted_values:
              values: ['< 25', '25-34', '35-44', '45-54', '55-64', '65+']

      - name: tenure_band
        description: Tenure band of terminated employee
        data_tests:
          - not_null
          - accepted_values:
              values: ['< 2', '2-4', '5-9', '10-19', '20+']

      - name: level_id
        description: Job level of terminated employee
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_config_job_levels')
              field: level_id

      - name: termination_type
        description: Type of termination processing
        data_tests:
          - not_null
          - accepted_values:
              values: ['hazard_termination', 'gap_filling']

  - name: int_hiring_events
    description: >
      New employee hiring events generated to replace departures and achieve target growth.
      Uses modulo-based date distribution for even hiring throughout the year.

      Key features:
      - Even distribution of hire dates across all 365 days of the year
      - Deterministic behavior preserved (same sequence_num = same date)
      - No clustering at December 31st
      - Realistic hiring patterns for workforce simulation
    config:
      tags: ["event_sourcing", "critical"]

    columns:
      - name: employee_id
        description: Unique identifier for new hire
        data_tests:
          - unique
          - not_null

      - name: employee_ssn
        description: Generated SSN for new hire
        data_tests:
          - unique
          - not_null

      - name: event_type
        description: Type of event (always 'hire')
        data_tests:
          - not_null
          - accepted_values:
              values: ['hire']

      - name: simulation_year
        description: Year when hire occurs
        data_tests:
          - not_null

      - name: effective_date
        description: Specific date when hire is effective
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "cast('{{ var('simulation_year') }}-01-01' as date)"
              max_value: "cast('{{ var('simulation_year') }}-12-31' as date)"

      - name: employee_age
        description: Age of new hire
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 18
              max_value: 70

      - name: birth_date
        description: Birth date of new hire
        data_tests:
          - not_null

      - name: level_id
        description: Job level assigned to new hire
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_config_job_levels')
              field: level_id

      - name: compensation_amount
        description: Starting compensation for new hire
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 30000
              max_value: 500000

      - name: hire_source
        description: Source of hire (always 'external_hire')
        data_tests:
          - not_null
          - accepted_values:
              values: ['external_hire']

      - name: created_at
        description: Timestamp when record was created
        data_tests:
          - not_null

    # Custom data quality tests to prevent date clustering regression
    data_tests:
      - dbt_utils.expression_is_true:
          expression: "(select round(count(case when extract(month from effective_date) = 12 then 1 end) * 100.0 / count(*), 2) from int_hiring_events) <= 15.0"
          config:
            severity: error
            error_if: ">= 1"

      - dbt_utils.expression_is_true:
          expression: "(select count(distinct effective_date) from int_hiring_events) >= 300"
          config:
            severity: error
            error_if: ">= 1"

  - name: int_effective_parameters
    description: >
      Parameter resolution model that determines effective parameters per scenario, year, level, and event type.
      Provides dynamic parameter lookup with scenario-based overrides and fallback to defaults.

      Key features:
      - Scenario-based parameter resolution with fallback hierarchy
      - Support for parameter locking to prevent changes
      - Audit trail of parameter sources (scenario, default, hardcoded)
      - Optimized for real-time parameter lookup during simulation
    config:
      tags: ["critical", "foundation"]

    columns:
      - name: parameter_key
        description: Unique key for parameter combination
        data_tests:
          - unique
          - not_null

      - name: scenario_id
        description: Scenario identifier for this parameter set
        data_tests:
          - not_null

      - name: fiscal_year
        description: Fiscal year for which this parameter applies
        data_tests:
          - not_null

      - name: job_level
        description: Job level (1-5) for which this parameter applies
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5

      - name: event_type
        description: Workforce event type for this parameter
        data_tests:
          - not_null
          - accepted_values:
              values: ['RAISE', 'PROMOTION', 'TERMINATION', 'HIRE']

      - name: parameter_name
        description: Name of the parameter
        data_tests:
          - not_null

      - name: parameter_value
        description: Resolved parameter value
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

      - name: is_locked
        description: Whether this parameter is locked from changes
        data_tests:
          - not_null

      - name: parameter_source
        description: Source of the parameter value (scenario, default, hardcoded)
        data_tests:
          - not_null
          - accepted_values:
              values: ['scenario', 'default', 'hardcoded']

      - name: resolved_at
        description: Timestamp when parameter was resolved
        data_tests:
          - not_null

  - name: int_merit_events
    description: >
      Merit-based compensation increases applied to eligible employees.
      Uses dynamic parameter resolution for merit rates by job level and year.
    config:
      tags: ["event_sourcing", "critical"]
    columns:
      - name: employee_id
        description: Unique identifier for employee receiving merit increase
        data_tests:
          - not_null
      - name: event_type
        description: Type of event (always 'RAISE')
        data_tests:
          - not_null
          - accepted_values:
              values: ['RAISE']
      - name: simulation_year
        description: Year when merit increase occurs
        data_tests:
          - not_null
      - name: effective_date
        description: Date when merit increase becomes effective
        data_tests:
          - not_null
      - name: compensation_amount
        description: New compensation amount after merit increase
        data_tests:
          - not_null

  - name: int_promotion_events
    description: >
      Promotion events for employees advancing to higher job levels.
      Uses hazard-based probability models with demographic factors.
    config:
      tags: ["event_sourcing", "critical"]
    columns:
      - name: employee_id
        description: Unique identifier for promoted employee
        data_tests:
          - not_null
      - name: event_type
        description: Type of event (always 'promotion')
        data_tests:
          - not_null
          - accepted_values:
              values: ['promotion']
      - name: simulation_year
        description: Year when promotion occurs
        data_tests:
          - not_null
      - name: effective_date
        description: Date when promotion becomes effective
        data_tests:
          - not_null
      - name: new_level_id
        description: New job level after promotion
        data_tests:
          - not_null
      - name: compensation_amount
        description: New compensation amount after promotion
        data_tests:
          - not_null

  - name: int_new_hire_termination_events
    description: >
      Termination events for employees hired in the same simulation year.
      Applies higher turnover rates to new hires for realistic modeling.
    config:
      tags: ["event_sourcing"]
    columns:
      - name: employee_id
        description: Unique identifier for terminated new hire
        data_tests:
          - not_null
      - name: event_type
        description: Type of event (always 'termination')
        data_tests:
          - not_null
          - accepted_values:
              values: ['termination']
      - name: simulation_year
        description: Year when termination occurs
        data_tests:
          - not_null
      - name: effective_date
        description: Date when termination becomes effective
        data_tests:
          - not_null
