version: 2
updates:
  - package-ecosystem: npm
    directory: /planalign_studio
    schedule:
      interval: weekly
      day: monday
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      python-dependencies:
        patterns:
          - "*"
