repos:
  # Basic syntax and formatting checks that don't require full environment
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags used by dbt
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  # Python syntax validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast  # Python syntax check

  # Local validation reminder (non-blocking)
  - repo: local
    hooks:
      - id: ci-reminder
        name: ci-validation-reminder
        entry: bash -c 'echo "💡 Remember to run ./scripts/run_ci_tests.sh before pushing for full validation"'
        language: system
        files: '(dbt/.*\.(sql|yml|yaml)|orchestrator/.*\.py)$'
        pass_filenames: false
        verbose: true
