# Example Benchmark Configuration
# Copy to benchmark_config.yaml and customize as needed

# Global benchmark settings
benchmark:
  # Output directory for benchmark results
  output_directory: "./benchmark_results"

  # Baseline directory for regression detection
  baseline_directory: "./benchmark_baselines"

  # Default random seed for reproducible results
  random_seed: 12345

  # Number of runs per scenario for statistical validity
  default_runs: 3

  # Default scenarios to run
  default_scenarios:
    - quick
    - 1kx3

  # Default modes to test
  default_modes:
    - sql
    - polars

# Scenario configurations
scenarios:
  quick:
    description: "Quick validation test with minimal data"
    employee_count: 100
    start_year: 2025
    end_year: 2026
    target_time_seconds: 5.0
    expected_events_range: [50, 500]

  1kx3:
    description: "1k employees × 3 years - development testing"
    employee_count: 1000
    start_year: 2025
    end_year: 2027
    target_time_seconds: 10.0
    expected_events_range: [1000, 10000]

  5kx5:
    description: "5k employees × 5 years - production target"
    employee_count: 5000
    start_year: 2025
    end_year: 2029
    target_time_seconds: 60.0
    expected_events_range: [10000, 100000]

  stress:
    description: "10k employees × 10 years - stress testing"
    employee_count: 10000
    start_year: 2025
    end_year: 2034
    target_time_seconds: 300.0
    expected_events_range: [50000, 500000]

# Performance monitoring settings
monitoring:
  # Resource monitoring interval in seconds
  monitoring_interval: 0.5

  # Memory usage alert threshold (MB)
  memory_alert_threshold: 4000

  # CPU usage alert threshold (%)
  cpu_alert_threshold: 90

  # Enable detailed system monitoring
  enable_detailed_monitoring: true

# Regression detection settings
regression:
  # Time regression threshold (percentage slower)
  time_regression_threshold: 0.15  # 15%

  # Throughput regression threshold (percentage fewer events/sec)
  throughput_regression_threshold: 0.10  # 10%

  # Memory regression threshold (percentage more memory)
  memory_regression_threshold: 0.20  # 20%

  # Minimum number of runs for statistical analysis
  minimum_runs_for_stats: 3

  # Confidence level for statistical tests
  confidence_level: 0.95

# Report generation settings
reporting:
  # Enable JSON report generation
  enable_json: true

  # Enable CSV report generation
  enable_csv: true

  # Enable Markdown report generation
  enable_markdown: true

  # Include detailed run data in reports
  include_detailed_data: true

  # Include statistical analysis
  include_statistics: true

  # Include performance recommendations
  include_recommendations: true

# CI/CD integration settings
ci_cd:
  # Fail CI on performance regression
  fail_on_regression: true

  # Performance gate scenarios
  performance_gate_scenarios:
    - scenario: 5kx5
      mode: polars
      target_time: 60.0

  # Daily monitoring scenarios
  daily_monitoring_scenarios:
    - quick
    - 1kx3
    - 5kx5

  # Baseline update scenarios
  baseline_scenarios:
    - quick
    - 1kx3
    - 5kx5

# Polars-specific settings
polars:
  # Maximum threads for parallel processing
  max_threads: 16

  # Batch size for processing
  batch_size: 10000

  # Enable compression for output files
  enable_compression: true

  # Compression level (1-22 for zstd)
  compression_level: 6

  # Enable lazy evaluation
  lazy_evaluation: true

  # Enable streaming mode
  streaming: true

  # Memory limit in GB
  max_memory_gb: 8.0

# SQL-specific settings
sql:
  # Number of dbt threads
  dbt_threads: 1

  # Enable incremental processing
  enable_incremental: true

  # dbt selection patterns
  foundation_selection: "tag:foundation"
  events_selection: "tag:EVENT_GENERATION"

  # Command timeout in seconds
  command_timeout: 600

# Logging settings
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR)
  level: INFO

  # Enable file logging
  enable_file_logging: true

  # Log file rotation
  rotate_logs: true

  # Maximum log file size (MB)
  max_log_size_mb: 100

  # Number of backup log files
  backup_count: 5

# Development settings
development:
  # Enable dry run mode for testing
  enable_dry_run: false

  # Enable verbose output for debugging
  verbose_mode: false

  # Enable profiling for performance analysis
  enable_profiling: false

  # Skip validation for faster development
  skip_validation: false
