"""Measurement campaign driver for the run-cost profile (Feature 116).

Runs the same multi-year simulation against each census size in a fresh,
isolated DuckDB (never ``dbt/simulation.duckdb``), recording one TimingSample
JSON per repetition plus a campaign-level summary (SC-007 hash evidence and
the FR-004 minimal-invocation floor).

Usage:
    python -m scripts.perf_profile.run_matrix --sizes tiny,dev,large --reps 3
    python -m scripts.perf_profile.run_matrix --sizes tiny --reps 1   # smoke
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import subprocess
import sys
import threading
import time
from contextlib import contextmanager
from datetime import datetime, timezone
from importlib import metadata
from pathlib import Path
from typing import Iterator, List, Optional

import duckdb
import psutil

from .dbt_timing import InvocationRecorder, attach_stage_tracking
from .profile_config import (
    DEV_CENSUS_PARQUET,
    LARGE_CENSUS_PARQUET,
    MEMORY_CENSUS_PARQUET,
    ROOT,
    OUTPUT_DIR,
    SHARED_DEV_DB,
    TINY_CENSUS_CSV,
    CampaignSummary,
    CensusSize,
    EnvNote,
    FloorStats,
    TimingSample,
)

CONFIG_YAML = ROOT / "config" / "simulation_config.yaml"
FLOOR_SELECTOR = "stg_config_age_bands"  # trivial config-seed model (analysis U2)


def _sha256(path: Path) -> Optional[str]:
    if not path.exists():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _git_sha() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=ROOT
        )
        return out.stdout.strip() or "unknown"
    except OSError:
        return "unknown"


def _version(pkg: str) -> str:
    try:
        return metadata.version(pkg)
    except metadata.PackageNotFoundError:
        return "unknown"


def build_env_note(shared_db_sha: Optional[str]) -> EnvNote:
    return EnvNote(
        machine=f"{platform.machine()} cpus={os.cpu_count()}",
        os=platform.platform(),
        python=platform.python_version(),
        dbt_core=_version("dbt-core"),
        dbt_duckdb=_version("dbt-duckdb"),
        duckdb=duckdb.__version__,
        git_sha=_git_sha(),
        shared_db_sha256_before=shared_db_sha,
    )


@contextmanager
def database_environment(database: Path) -> Iterator[None]:
    previous = os.environ.get("DATABASE_PATH")
    os.environ["DATABASE_PATH"] = str(database)
    try:
        yield
    finally:
        if previous is None:
            os.environ.pop("DATABASE_PATH", None)
        else:
            os.environ["DATABASE_PATH"] = previous


def ensure_tiny_parquet() -> Path:
    path = OUTPUT_DIR / "census_tiny.parquet"
    if not path.exists():
        with duckdb.connect() as conn:
            conn.read_csv(str(TINY_CENSUS_CSV)).write_parquet(str(path))
    return path


def resolve_census(size: CensusSize) -> Path:
    paths = {
        CensusSize.TINY: ensure_tiny_parquet(),
        CensusSize.DEV: DEV_CENSUS_PARQUET,
        CensusSize.LARGE: LARGE_CENSUS_PARQUET,
        CensusSize.MEMORY: MEMORY_CENSUS_PARQUET,
    }
    path = paths[size]
    if not path.exists():
        raise FileNotFoundError(
            f"census for size '{size.value}' missing: {path} "
            "(large/memory inputs are generated by "
            "scripts.perf_profile.make_large_census)"
        )
    return path


def _census_rows(parquet: Path) -> int:
    with duckdb.connect() as conn:
        return conn.sql(f"SELECT COUNT(*) FROM read_parquet('{parquet}')").fetchone()[0]


def _load_config(census_parquet: Path, horizon: tuple[int, int]):
    from planalign_orchestrator.config import load_simulation_config

    config = load_simulation_config(CONFIG_YAML, env_overrides=False)
    config.setup["census_parquet_path"] = str(census_parquet)
    config.simulation.start_year = horizon[0]
    config.simulation.end_year = horizon[1]
    return config


def _config_fingerprint(config) -> str:
    payload = config.model_dump(mode="json")
    optimization = dict(payload.get("optimization") or {})
    optimization.pop("execution_engine", None)
    payload["optimization"] = optimization
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


class _PeakRssMonitor:
    """Sample recursive process-tree RSS while one campaign run executes."""

    def __init__(self) -> None:
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._sample, daemon=True)
        self.peak_bytes = 0

    def start(self) -> None:
        self._thread.start()

    def stop(self) -> float:
        self._stop.set()
        self._thread.join(timeout=2)
        return self.peak_bytes / (1024 * 1024)

    def _sample(self) -> None:
        process = psutil.Process()
        while not self._stop.wait(0.1):
            processes = [process, *process.children(recursive=True)]
            total = 0
            for item in processes:
                try:
                    total += item.memory_info().rss
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    continue
            self.peak_bytes = max(self.peak_bytes, total)


def run_single(
    size: CensusSize,
    repetition: int,
    *,
    warm: bool,
    horizon: tuple[int, int],
    shared_db_sha: Optional[str],
    campaign_id: str,
    engine: str,
    db_dir: Path,
) -> TimingSample:
    """Execute one isolated simulation and return its TimingSample."""
    from planalign_orchestrator import create_orchestrator

    census = resolve_census(size)
    # Underscore only: the file stem becomes the DuckDB database alias, and
    # dbt-duckdb references it unquoted — a hyphen breaks every dbt statement.
    db_path = db_dir / f"{campaign_id}_{engine}_{size.value}_{repetition}.duckdb"
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()
    if db_path.resolve() == SHARED_DEV_DB.resolve():
        raise RuntimeError("guardrail: refusing to run against the shared dev DB")

    config = _load_config(census, horizon)
    config.optimization.execution_engine = engine
    error: Optional[str] = None
    recorder: Optional[InvocationRecorder] = None
    start = time.perf_counter()
    memory = _PeakRssMonitor()
    memory.start()
    orchestrator = None
    try:
        with database_environment(db_path):
            orchestrator = create_orchestrator(config, db_path=db_path, threads=1)
            recorder = InvocationRecorder(orchestrator.dbt_runner)
            attach_stage_tracking(orchestrator, recorder)
            orchestrator.execute_multi_year_simulation(
                start_year=horizon[0], end_year=horizon[1]
            )
    except BaseException as exc:  # sample must record failures, never drop them
        error = f"{type(exc).__name__}: {exc}"
    finally:
        total_wall = time.perf_counter() - start
        peak_rss_mb = memory.stop()
        if recorder is not None:
            recorder.unwrap()

    record_log = getattr(getattr(orchestrator, "dbt_runner", None), "record_log", None)
    delegated = len(record_log.delegations) if record_log is not None else 0
    unexpected = record_log.fallback_count if record_log is not None else 0
    return TimingSample(
        sample_id=f"{campaign_id}-{engine}-{size.value}-{repetition}",
        campaign_id=campaign_id,
        engine=engine,
        census_size=size,
        census_rows=_census_rows(census),
        census_parquet=str(census),
        census_fingerprint=_sha256(census),
        config_fingerprint=_config_fingerprint(config),
        horizon=horizon,
        repetition=repetition,
        warm=warm,
        db_path=str(db_path),
        total_wall_s=total_wall,
        invocations=recorder.invocations if recorder else [],
        env=build_env_note(shared_db_sha),
        completed=error is None,
        error=error,
        delegated_invocation_count=delegated,
        unexpected_fallback_count=unexpected,
        peak_rss_mb=peak_rss_mb,
    )


def write_sample(sample: TimingSample, samples_dir: Path) -> Path:
    samples_dir.mkdir(parents=True, exist_ok=True)
    path = samples_dir / f"{sample.sample_id}.json"
    path.write_text(sample.model_dump_json(indent=2))
    return path


def measure_floor(
    built_db: Path, census_parquet: Path, samples_dir: Path, reps: int = 5
) -> FloorStats:
    """Time a minimal dbt invocation against an already-built DB (FR-004)."""
    from planalign_orchestrator.config.export import to_dbt_vars
    from planalign_orchestrator.dbt_runner import DbtRunner

    config = _load_config(census_parquet, (2025, 2027))
    dbt_vars = to_dbt_vars(config)
    runner = DbtRunner(working_dir=ROOT / "dbt", threads=1, verbose=False)
    walls: List[float] = []
    executes: List[float] = []
    with database_environment(built_db):
        for _ in range(reps):
            start = time.perf_counter()
            result = runner.execute_command(
                ["run", "--select", FLOOR_SELECTOR],
                simulation_year=2025,
                dbt_vars=dbt_vars,
                stream_output=False,
                retry=False,
            )
            walls.append(time.perf_counter() - start)
            if not result.success:
                raise RuntimeError(f"floor measurement failed: {result.stderr[-500:]}")
            from .dbt_timing import _parse_run_results

            models = _parse_run_results(ROOT / "dbt" / "target")
            executes.append(sum(m.execute_s for m in models))
    return FloorStats(
        selector=FLOOR_SELECTOR,
        reps=reps,
        wall_s=walls,
        execute_s=executes,
        invocations_per_year=_invocations_per_year(samples_dir),
    )


def _invocations_per_year(samples_dir: Path) -> int:
    """Median invocation count per simulated year across completed samples."""
    counts: List[int] = []
    for path in sorted(samples_dir.glob("*-*.json")):
        sample = TimingSample.model_validate_json(path.read_text())
        if not sample.completed or not sample.invocations:
            continue
        years = sample.horizon[1] - sample.horizon[0] + 1
        counts.append(round(len(sample.invocations) / years))
    if not counts:
        raise RuntimeError("no completed samples to derive invocations/year from")
    return sorted(counts)[len(counts) // 2]


def _parse_horizon(text: str) -> tuple[int, int]:
    start, _, end = text.partition("-")
    return int(start), int(end)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sizes", default="tiny,dev,large")
    parser.add_argument("--campaign-id", default="feature119")
    parser.add_argument("--engines", default="dbt,compiled")
    parser.add_argument(
        "--reps",
        type=int,
        default=3,
        help="warm repetitions (a cold rep 0 is always prepended)",
    )
    parser.add_argument("--horizon", default="2025-2027")
    parser.add_argument("--measure-floor", action="store_true")
    parser.add_argument(
        "--skip-cold",
        action="store_true",
        help="skip the automatic cold run (reuse existing rep 0)",
    )
    args = parser.parse_args(argv)

    sizes = [CensusSize(s.strip()) for s in args.sizes.split(",") if s.strip()]
    engines = [value.strip() for value in args.engines.split(",") if value.strip()]
    invalid_engines = set(engines) - {"dbt", "compiled"}
    if invalid_engines:
        parser.error(f"unsupported engines: {sorted(invalid_engines)}")
    horizon = _parse_horizon(args.horizon)
    campaign_root = OUTPUT_DIR / args.campaign_id
    samples_dir = campaign_root / "samples"
    db_dir = campaign_root / "db"
    campaign_path = campaign_root / "campaign.json"
    samples_dir.mkdir(parents=True, exist_ok=True)
    db_dir.mkdir(parents=True, exist_ok=True)

    sha_before = _sha256(SHARED_DEV_DB)
    if campaign_path.exists():
        # Continue the existing campaign: keep its start, before-hash, and floor.
        campaign = CampaignSummary.model_validate_json(campaign_path.read_text())
        campaign.sizes_run = sorted(set(campaign.sizes_run) | {s.value for s in sizes})
        campaign.engines_run = sorted(set(campaign.engines_run) | set(engines))
        sha_before = campaign.shared_db_sha256_before
    else:
        campaign = CampaignSummary(
            started_at=datetime.now(timezone.utc).isoformat(),
            campaign_id=args.campaign_id,
            shared_db_sha256_before=sha_before,
            sizes_run=[s.value for s in sizes],
            engines_run=engines,
        )

    exit_code = 0
    last_completed_db: Optional[tuple[Path, Path]] = None
    for size in sizes:
        reps: List[tuple[int, bool]] = [] if args.skip_cold else [(0, False)]
        reps += [(i, True) for i in range(1, args.reps + 1)]
        for repetition, warm in reps:
            ordered_engines = (
                engines if repetition % 2 == 0 else list(reversed(engines))
            )
            for engine in ordered_engines:
                label = "warm" if warm else "cold"
                print(
                    f"[run_matrix] {engine} {size.value} rep {repetition} "
                    f"({label}) ...",
                    flush=True,
                )
                sample = run_single(
                    size,
                    repetition,
                    warm=warm,
                    horizon=horizon,
                    shared_db_sha=sha_before,
                    campaign_id=args.campaign_id,
                    engine=engine,
                    db_dir=db_dir,
                )
                path = write_sample(sample, samples_dir)
                status = "ok" if sample.completed else f"FAILED: {sample.error}"
                print(
                    f"[run_matrix]   {sample.total_wall_s:.1f}s total, "
                    f"{sample.peak_rss_mb:.1f} MiB peak RSS, "
                    f"{len(sample.invocations)} invocations -> {path.name} "
                    f"[{status}]",
                    flush=True,
                )
                if not sample.completed:
                    exit_code = 1
                elif warm and engine == "dbt":
                    last_completed_db = (
                        Path(sample.db_path),
                        Path(sample.census_parquet),
                    )

    if args.measure_floor:
        if last_completed_db is None:
            print("[run_matrix] no completed run available for floor measurement")
            exit_code = 1
        else:
            db, census = last_completed_db
            print(
                f"[run_matrix] measuring invocation floor against {db.name} ...",
                flush=True,
            )
            campaign.floor = measure_floor(db, census, samples_dir)
            print(
                f"[run_matrix]   floor median {campaign.floor.median_floor_s:.1f}s x "
                f"{campaign.floor.invocations_per_year} invocations/year",
                flush=True,
            )

    sha_after = _sha256(SHARED_DEV_DB)
    campaign.finished_at = datetime.now(timezone.utc).isoformat()
    campaign.shared_db_sha256_after = sha_after
    campaign.shared_db_unchanged = sha_before == sha_after
    campaign_path.write_text(campaign.model_dump_json(indent=2))

    if campaign.shared_db_unchanged:
        print("[run_matrix] shared dev DB unchanged (sha256 verified)")
    else:
        print("[run_matrix] ERROR: shared dev DB hash changed during campaign!")
        exit_code = 2
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
