-- E068A: Fused Event Generation - Optimized single-model approach
-- Reduces Event Generation wall-time by ~2× by replacing many small per-event models
-- with a single per-year compiled query that eliminates intermediate materialization
--
-- E068G: Hybrid SQL/Polars Integration
-- Supports both SQL-based event generation (traditional) and Polars-based event generation
-- (high-performance vectorized approach). Automatically switches based on event_generation_mode.

{{ config(
  materialized='incremental',
  unique_key=['scenario_id', 'plan_design_id', 'simulation_year'],
  incremental_strategy='delete+insert',
  on_schema_change='sync_all_columns',
  tags=['EVENT_GENERATION']
) }}

{% set simulation_year = var('simulation_year', 2025) %}
{% set event_mode = var('event_generation_mode', 'sql') %}

{% if event_mode == 'polars' %}

-- ===================================================================
-- POLARS MODE: Read events from Polars bulk event factory Parquet files
-- ===================================================================
-- Events are generated by the Polars vectorized engine and written to
-- partitioned Parquet files. This provides 375× performance improvement
-- over SQL-based generation.

WITH polars_raw_events AS (
  SELECT
    -- Use event_id if available, otherwise generate one
    COALESCE(
      event_id,
      MD5(CONCAT(
        CAST(scenario_id AS VARCHAR), '|',
        CAST(plan_design_id AS VARCHAR), '|',
        employee_id, '|',
        CAST(simulation_year AS VARCHAR), '|',
        event_type
      ))
    ) AS event_id,
    -- Cast IDs to VARCHAR (Polars may output as INT)
    COALESCE(CAST(scenario_id AS VARCHAR), '{{ var("scenario_id", "default") }}') AS scenario_id,
    COALESCE(CAST(plan_design_id AS VARCHAR), '{{ var("plan_design_id", "default") }}') AS plan_design_id,
    employee_id,
    -- Read demographic fields from Polars output (now included)
    employee_ssn,
    event_type,
    simulation_year,
    COALESCE(effective_date, event_date) AS effective_date,

    -- Use event_details if available, otherwise extract from JSON payload
    COALESCE(event_details, event_payload::text, '') AS event_details,

    -- Read compensation_amount directly if available, otherwise extract from JSON
    COALESCE(
      compensation_amount,
      CASE
        WHEN event_type IN ('promotion', 'merit') THEN
          TRY_CAST(json_extract_string(event_payload, '$.new_salary') AS DECIMAL(10,2))
        WHEN event_type = 'hire' THEN
          TRY_CAST(json_extract_string(event_payload, '$.starting_salary') AS DECIMAL(10,2))
        ELSE NULL
      END
    ) AS compensation_amount,

    COALESCE(
      previous_compensation,
      CASE
        WHEN event_type IN ('promotion', 'merit') THEN
          TRY_CAST(json_extract_string(event_payload, '$.old_salary') AS DECIMAL(10,2))
        ELSE NULL
      END
    ) AS previous_compensation,

    -- Read deferral rates (with fallback to JSON extraction)
    COALESCE(
      employee_deferral_rate,
      CASE
        WHEN event_type = 'benefit_enrollment' THEN
          TRY_CAST(json_extract_string(event_payload, '$.initial_deferral_rate') AS DECIMAL(5,4))
        ELSE NULL
      END
    ) AS employee_deferral_rate,

    prev_employee_deferral_rate,
    -- Read demographic fields directly from Polars output (now included)
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,

    -- Use event_category if available, otherwise infer from event_type
    COALESCE(
      event_category,
      CASE
        WHEN event_type IN ('hire', 'termination') THEN 'workforce'
        WHEN event_type IN ('promotion', 'merit') THEN 'compensation'
        WHEN event_type LIKE '%enrollment%' THEN 'benefits'
        WHEN event_type LIKE 'deferral%' THEN 'benefits'
        ELSE 'other'
      END
    ) AS event_category,

    created_at,
    '{{ var("scenario_id", "default") }}' AS parameter_scenario_id,
    COALESCE(generation_method, 'polars_factory') AS parameter_source,
    'VALID' AS data_quality_flag  -- Polars events are pre-validated

  FROM read_parquet('{{ var("polars_events_path", "../data/parquet/events") }}/simulation_year={{ simulation_year }}/*.parquet')
),

-- Add event sequencing for conflict resolution
final_events AS (
  SELECT
    event_id,
    scenario_id,
    plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category,
    -- Add event sequencing for conflict resolution
    -- Priority: termination(1) > hire(2) > eligibility(3) > enrollment(4) > enrollment_change(5) > deferral_escalation(6) > promotion(7) > merit_increase(8)
    ROW_NUMBER() OVER (
      PARTITION BY scenario_id, plan_design_id, employee_id, simulation_year
      ORDER BY
        CASE event_type
          WHEN 'termination' THEN 1
          WHEN 'hire' THEN 2
          WHEN 'eligibility' THEN 3
          WHEN 'enrollment' THEN 4
          WHEN 'enrollment_change' THEN 5
          WHEN 'deferral_match_response' THEN 6
          WHEN 'deferral_escalation' THEN 7
          WHEN 'promotion' THEN 8
          WHEN 'raise' THEN 8
          WHEN 'merit' THEN 8
          ELSE 9
        END,
        effective_date
    ) AS event_sequence,
    created_at,
    parameter_scenario_id,
    parameter_source,
    data_quality_flag
  FROM polars_raw_events
)

SELECT * FROM final_events

{% else %}

-- ===================================================================
-- SQL MODE: Traditional dbt-based event generation
-- ===================================================================
-- E068A: Fused Event Generation Implementation
-- Single compiled query per year that references ephemeral event models
-- and combines them into the final events table

WITH all_events AS (
  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category
  FROM {{ ref('int_hiring_events') }}
  WHERE simulation_year = {{ simulation_year }}

  UNION ALL

  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category
  FROM {{ ref('int_termination_events') }}
  WHERE simulation_year = {{ simulation_year }}

  UNION ALL

  -- E068A: Include new-hire termination events (ephemeral) in fused output
  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    nht.employee_id,
    nht.employee_ssn,
    nht.event_type,
    nht.simulation_year,
    nht.effective_date,
    'Termination - ' || nht.termination_reason || ' (final compensation: $' || CAST(ROUND(nht.final_compensation, 0) AS VARCHAR) || ')' AS event_details,
    nht.final_compensation AS compensation_amount,
    nht.final_compensation AS previous_compensation,
    NULL::DECIMAL(5,4) AS employee_deferral_rate,
    NULL::DECIMAL(5,4) AS prev_employee_deferral_rate,
    nht.current_age AS employee_age,
    nht.current_tenure AS employee_tenure,
    nht.level_id,
    nht.age_band,
    nht.tenure_band,
    nht.termination_rate AS event_probability,
    nht.event_category  -- E021 FIX: Use source event_category instead of hardcoded 'termination'
  FROM {{ ref('int_new_hire_termination_events') }} nht
  WHERE nht.simulation_year = {{ simulation_year }}

  UNION ALL

  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category
  FROM {{ ref('int_promotion_events') }}
  WHERE simulation_year = {{ simulation_year }}

  UNION ALL

  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category
  FROM {{ ref('int_merit_events') }}
  WHERE simulation_year = {{ simulation_year }}

  UNION ALL

  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category
  FROM {{ ref('int_enrollment_events') }}
  WHERE simulation_year = {{ simulation_year }}

  UNION ALL

  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category
  FROM {{ ref('int_deferral_rate_escalation_events') }}
  WHERE simulation_year = {{ simulation_year }}

  UNION ALL

  -- E058: Match-responsive deferral adjustment events
  SELECT
    '{{ var('scenario_id', 'default') }}' AS scenario_id,
    '{{ var('plan_design_id', 'default') }}' AS plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category
  FROM {{ ref('int_deferral_match_response_events') }}
  WHERE simulation_year = {{ simulation_year }}
),

-- Final selection with event sequencing for conflict resolution
final_events AS (
  SELECT
    -- BUGFIX: Use deterministic hash-based event_id to prevent duplicates
    -- Hash combines all unique event attributes to guarantee uniqueness
    'EVT_' || SUBSTR(MD5(
      scenario_id || '_' ||
      plan_design_id || '_' ||
      employee_id || '_' ||
      CAST(simulation_year AS VARCHAR) || '_' ||
      event_type || '_' ||
      CAST(effective_date AS VARCHAR) || '_' ||
      COALESCE(CAST(compensation_amount AS VARCHAR), 'NULL')
    ), 1, 24) AS event_id,
    scenario_id,
    plan_design_id,
    employee_id,
    employee_ssn,
    event_type,
    simulation_year,
    effective_date,
    event_details,
    compensation_amount,
    previous_compensation,
    employee_deferral_rate,
    prev_employee_deferral_rate,
    employee_age,
    employee_tenure,
    level_id,
    age_band,
    tenure_band,
    event_probability,
    event_category,
    -- Add event sequencing for conflict resolution
    -- Priority: termination(1) > hire(2) > eligibility(3) > enrollment(4) > enrollment_change(5) > deferral_escalation(6) > promotion(7) > merit_increase(8)
    ROW_NUMBER() OVER (
      PARTITION BY scenario_id, plan_design_id, employee_id, simulation_year
      ORDER BY
        CASE event_type
          WHEN 'termination' THEN 1
          WHEN 'hire' THEN 2
          WHEN 'eligibility' THEN 3
          WHEN 'enrollment' THEN 4
          WHEN 'enrollment_change' THEN 5
          WHEN 'deferral_match_response' THEN 6
          WHEN 'deferral_escalation' THEN 7
          WHEN 'promotion' THEN 8
          WHEN 'raise' THEN 9  -- Note: 'raise' not 'RAISE' for consistency
          ELSE 10
        END,
        effective_date
    ) AS event_sequence,
    -- Add metadata for audit trail
    CURRENT_TIMESTAMP AS created_at,
    -- Add parameter tracking for dynamic compensation system
    '{{ var("scenario_id", "default") }}' AS parameter_scenario_id,
    'fused_event_generation' AS parameter_source,  -- E068A tracking
    -- Add data validation flags
    CASE
      WHEN employee_id IS NULL THEN 'INVALID_EMPLOYEE_ID'
      WHEN simulation_year IS NULL THEN 'INVALID_SIMULATION_YEAR'
      WHEN effective_date IS NULL THEN 'INVALID_EFFECTIVE_DATE'
      WHEN compensation_amount IS NULL AND event_type NOT IN ('termination','enrollment','enrollment_change','deferral_escalation') THEN 'INVALID_COMPENSATION'
      ELSE 'VALID'
    END AS data_quality_flag
  FROM all_events
  WHERE 1=1
  {%- if simulation_year %}
    AND simulation_year = {{ simulation_year }}
  {%- endif %}
    -- Exclude records with data quality issues
    AND (
      CASE
        WHEN employee_id IS NULL THEN 'INVALID_EMPLOYEE_ID'
        WHEN simulation_year IS NULL THEN 'INVALID_SIMULATION_YEAR'
        WHEN effective_date IS NULL THEN 'INVALID_EFFECTIVE_DATE'
        WHEN compensation_amount IS NULL AND event_type NOT IN ('termination','enrollment','enrollment_change','deferral_escalation') THEN 'INVALID_COMPENSATION'
        ELSE 'VALID'
      END
    ) = 'VALID'
)

-- Insert-overwrite by simulation_year with deterministic ordering for stable diffs
-- E068A: Single writer per year with explicit ORDER BY for reproducible results
SELECT * FROM final_events
-- Note: ORDER BY removed for incremental materialization compatibility
-- Some DuckDB contexts reject ORDER BY in INSERT SELECT statements for incremental models
-- ORDER BY scenario_id, plan_design_id, employee_id, simulation_year, event_type, effective_date

{% endif %}
