# PlanWise Navigator Orchestration Configuration
# Epic E043: Production Data Safety & Backup System

# Core simulation settings
simulation:
  start_year: 2025
  end_year: 2029
  random_seed: 42
  target_growth_rate: 0.03

# Compensation parameters
compensation:
  cola_rate: 0.005
  merit_budget: 0.025

# Workforce modeling
workforce:
  total_termination_rate: 0.12
  new_hire_termination_rate: 0.25

# Production data safety settings
production_safety:
  # Database configuration
  db_path: "simulation.duckdb"

  # Backup settings
  backup_enabled: true
  backup_dir: "backups"
  backup_retention_days: 7
  backup_before_simulation: true
  verify_backups: true
  max_backup_size_gb: 10.0

  # Logging configuration
  log_level: "INFO"
  log_dir: "logs"

  # Safety requirements
  require_backup_before_run: true
  enable_emergency_backups: true

# Enterprise identifiers (optional)
scenario_id: "default"
plan_design_id: "standard_401k"

# Enrollment settings
enrollment:
  auto_enrollment:
    enabled: true
    scope: "all_eligible_employees"
    hire_date_cutoff: null
    window_days: 45
    default_deferral_rate: 0.06
    opt_out_grace_period: 30
    opt_out_rates:
      by_age:
        young: 0.10
        mid_career: 0.07
        mature: 0.05
        senior: 0.03
      by_income:
        low_income: 1.20
        moderate: 1.00
        high: 0.70
        executive: 0.50

# Plan eligibility
eligibility:
  waiting_period_days: null

plan_eligibility:
  minimum_age: null
