# Asset-level configuration (used by simulation_config asset)
simulation:
  start_year: 2025
  end_year: 2029
  random_seed: 42
  target_growth_rate: 0.03


# Setup configuration for orchestrator_dbt
setup:
  clear_tables: true
  clear_mode: "year"  # Clear year-specific data only, preserve baseline
  clear_table_patterns: ["int_"]  # Only clear intermediate tables, preserve fact tables for multi-year accumulation
  load_seeds: true
  run_staging_models: true
  validate_results: false
  fail_on_validation_error: true
  census_parquet_path: "data/census_preprocessed.parquet"
  plan_year_start_date: "2024-01-01"
  plan_year_end_date: "2024-12-31"
  eligibility_waiting_period_days: 30

workforce:
  total_termination_rate: 0.12
  new_hire_termination_rate: 0.25

compensation:
  cola_rate: 0.01
  merit_budget: 0.02
  growth_target: 0.005
  growth_tolerance: 0.005
  calculation_methodology: "full_year_equivalent"  # options: current, continuous, full_year_equivalent

# Epic E056: New Hire Compensation Configurability
new_hire_compensation:
  # Compensation strategy selection
  strategy: "percentile_based"  # Options: percentile_based, custom_distribution, market_adjusted

  # Percentile-based hiring configuration
  percentile_strategy:
    default_percentile: 0.3    # 50th percentile (maintains current behavior)

    # Level-specific percentile overrides for strategic hiring
    level_overrides:
      1: 0.30                   # Level 1: 40th percentile (conservative for entry level)
      2: 0.40                   # Level 2: 50th percentile (baseline)
      3: 0.50                   # Level 3: 60th percentile (competitive)
      4: 0.65                   # Level 4: 75th percentile (aggressive for directors)
      5: 0.70                   # Level 5: 80th percentile (premium for executives)

    # Add realistic variance around target percentile
    variance_enabled: true
    variance_std_dev: 0.05      # 5% standard deviation for realism

  # Market adjustment multipliers (applied after percentile calculation)
  market_adjustments:
    enabled: true
    base_adjustment: 1.00       # No adjustment by default

    # Level-specific market adjustments
    level_adjustments:
      1: 1.02                   # 2% premium for entry level (competitive market)
      2: 1.00                   # No adjustment for managers
      3: 0.98                   # 2% discount for senior managers (cost control)
      4: 1.05                   # 5% premium for directors (talent retention)
      5: 1.10                   # 10% premium for VPs (executive competition)

    # Quick scenario multipliers for rapid modeling
    scenarios:
      conservative: 0.92        # 8% reduction for budget constraints
      baseline: 1.00            # No adjustment (default)
      competitive: 1.05         # 5% increase for competitive markets
      aggressive: 1.15          # 15% increase for talent war scenarios

  # Validation and bounds checking
  validation:
    min_percentile: 0.20        # Minimum allowable percentile (20th)
    max_percentile: 0.90        # Maximum allowable percentile (90th)
    min_market_adjustment: 0.80 # Minimum market adjustment (20% discount)
    max_market_adjustment: 1.30 # Maximum market adjustment (30% premium)

  # Future enhancement: Custom distribution modeling
  custom_distribution:
    enabled: false              # Disabled for initial implementation
    distribution_type: "beta"   # Options: normal, beta, uniform, custom
    parameters:
      alpha: 2.0
      beta: 5.0
      min_percentile: 0.25
      max_percentile: 0.85

raise_timing:
  methodology: "realistic"  # Options: "legacy", "realistic", "custom"
  distribution_profile: "general_corporate"  # Future: "technology", "finance", "government"
  validation_tolerance: 0.02  # ±2% tolerance for monthly distribution
  deterministic_behavior: true  # Ensure reproducible results

plan_year:
  start_date: "2024-01-01"  # Plan year start date for compensation calculations
  end_date: "2024-12-31"    # Plan year end date for compensation calculations
  annualization_method: "calendar_days"  # Method for annualizing partial year compensation (calendar_days vs work_days)

eligibility:
  waiting_period_days: 0  # Days employee must be employed before becoming eligible (0 = immediate, 365 = 1 year)
  # Future: moved to Epic E026
  # minimum_age: 21
  # minimum_hours_annual: 1000
  # excluded_employee_types: ["intern", "contractor"]
  # entry_date_type: "quarterly"

# Plan eligibility (separate from employer contribution eligibility)
plan_eligibility:
  waiting_period_days: 0  # Default: immediate eligibility for plan participation
  minimum_age: 21         # Minimum age to participate in the plan

# Epic E023: Enrollment Engine Configuration
enrollment:
  # Auto-enrollment configuration
  auto_enrollment:
    enabled: true  # Global auto-enrollment enable/disable toggle
    window_days: 45  # Configurable auto-enrollment window (default 45 days after hire)
    default_deferral_rate: 0.02  # 2% default deferral rate for auto-enrolled participants
    opt_out_grace_period: 30  # Days after auto-enrollment for opt-out without penalty
    scope: "new_hires_only"  # Options: "new_hires_only", "all_eligible_employees"
    hire_date_cutoff: "2025-01-01"  # Optional: Exclude employees hired before this date from auto-enrollment (e.g., "2020-01-01")

    # Opt-out rate configuration (industry-standard rates: 5-10% for well-designed programs)
    opt_out_rates:
      # Demographic-based opt-out rates (base rates)
      by_age:
        young: 0.10       # 10% opt-out rate for young employees (18-30)
        mid_career: 0.07  # 7% opt-out rate for mid-career employees (31-45)
        mature: 0.05      # 5% opt-out rate for mature employees (46-55)
        senior: 0.03      # 3% opt-out rate for senior employees (56+)

      # Income-based multipliers (applied to age-based rates)
      by_income:
        low_income: 1.20  # 20% higher opt-out for low income (was 1.60x = 60% higher)
        moderate: 1.00    # Base rate for moderate income
        high: 0.70        # 30% lower opt-out for high income (was 0.60x)
        executive: 0.50   # 50% lower opt-out for executives (was 0.20x)

    # Plan-specific overrides (future enhancement)
    plan_overrides:
      emergency_plan:
        enabled: false  # Disable auto-enrollment for emergency/temporary plans
        window_days: 30  # Shorter window for special plans
      executive_plan:
        enabled: true
        window_days: 60  # Longer window for executive plans
        default_deferral_rate: 0.10  # Higher default rate for executives

  # Proactive enrollment configuration (voluntary enrollment within auto-enrollment window)
  proactive_enrollment:
    enabled: true  # Enable proactive enrollment before auto-enrollment deadline
    timing_window:
      min_days: 7   # Earliest proactive enrollment (7 days after eligibility)
      max_days: 35  # Latest proactive enrollment (10 days before auto-enrollment deadline)
    probability_by_demographics:
      young: 0.25      # Ages 18-30: Lower proactive enrollment rate
      mid_career: 0.45 # Ages 31-45: Moderate proactive enrollment rate
      mature: 0.65     # Ages 46-55: Higher proactive enrollment rate
      senior: 0.75     # Ages 56+: Highest proactive enrollment rate
    timing_distribution:
      immediate: 0.2   # Within 30 days of eligibility
      early: 0.3       # 31-120 days after eligibility
      mid: 0.3         # 121-270 days after eligibility
      late: 0.2        # 271+ days after eligibility

  # Voluntary-only enrollment (for plans without auto-enrollment)
  voluntary_enrollment:
    enabled: true  # Enable voluntary enrollment for non-auto-enrollment plans
    annual_enrollment_probability: 0.60  # Base probability of voluntary enrollment

    # Epic E053: Enhanced demographic-based enrollment probabilities
    base_rates_by_age:
      young: 0.30      # Ages 18-30: 30% base enrollment rate
      mid_career: 0.55 # Ages 31-45: 55% base enrollment rate
      mature: 0.70     # Ages 46-55: 70% base enrollment rate
      senior: 0.80     # Ages 56+: 80% base enrollment rate

    income_multipliers:
      low: 0.70        # <$50k: Lower enrollment (financial constraints)
      moderate: 1.00   # $50k-$100k: Baseline enrollment
      high: 1.15       # $100k-$200k: Higher enrollment
      executive: 1.25  # >$200k: Highest enrollment

    job_level_multipliers:
      individual: 0.90 # Levels 1-2: Individual contributors
      senior: 1.00     # Levels 3-4: Senior individual contributors
      manager: 1.10    # Levels 5-6: Management roles
      executive: 1.20  # Levels 7+: Executive roles

    # Deferral rate selection with match optimization
    deferral_rates:
      match_optimization: true  # Enable match-maximizing behavior
      demographic_base_rates:
        young_low: 0.03       # Young, low income: 3%
        young_moderate: 0.03  # Young, moderate income: 3%
        young_high: 0.04      # Young, high income: 4%
        young_executive: 0.06 # Young, executive: 6%
        mid_career_low: 0.04
        mid_career_moderate: 0.06
        mid_career_high: 0.08
        mid_career_executive: 0.10
        mature_low: 0.05
        mature_moderate: 0.08
        mature_high: 0.10
        mature_executive: 0.12
        senior_low: 0.06
        senior_moderate: 0.10
        senior_high: 0.12
        senior_executive: 0.15

    demographic_adjustments:
      age_factor_per_year: 0.01    # +1% per year over 25
      tenure_factor_per_year: 0.05 # +5% per year of service
      salary_factor_high_earner: 0.15  # +15% for high earners (>$100k)
    timing_distribution:
      open_enrollment_period: 0.70  # 70% enroll during open enrollment
      mid_year_life_events: 0.20    # 20% enroll due to life events
      new_hire_immediate: 0.10      # 10% enroll immediately upon hire

  # Epic E053: Year-over-year voluntary enrollment for non-participants
  year_over_year_conversion:
    enabled: true  # Enable year-over-year voluntary enrollment
    base_rates_by_age:
      young: 0.03      # 3% annual conversion for ages 18-30
      mid_career: 0.05 # 5% annual conversion for ages 31-45
      mature: 0.07     # 7% annual conversion for ages 46-55
      senior: 0.08     # 8% annual conversion for ages 56+
    income_multipliers:
      low_income: 0.8  # Financial constraints reduce conversion
      moderate: 1.0    # Baseline conversion rate
      high: 1.2        # Increased financial capacity
      executive: 1.3   # Financial sophistication drives conversion
    tenure_multipliers:
      new_employee: 0.7  # < 2 years: Still adjusting
      established: 1.0   # 2-5 years: Baseline conversion
      veteran: 1.1       # 5+ years: Company loyalty/stability
    timing:
      enrollment_month: 6  # Mid-year enrollment events
      enrollment_day: 15   # 15th of the month
    deferral_rates:
      conservative: true  # Use conservative rates for new voluntary enrollees
      young: 0.03         # 3% for young converters
      mid_career: 0.04    # 4% for mid-career converters
      mature: 0.05        # 5% for mature converters
      senior: 0.06        # 6% for senior converters

  # Timing coordination and orchestration
  timing:
    processing_frequency: "monthly"  # Options: "daily", "weekly", "monthly", "quarterly"
    proactive_cutoff_before_auto: 10  # Days before auto-enrollment deadline for proactive enrollment
    deterministic_timing: true       # Ensure reproducible simulation results
    business_day_adjustment: true    # Adjust enrollment dates to business days
    holiday_calendar: "us_federal"   # Holiday calendar for business day calculations

  # Multi-year simulation considerations
  multi_year:
    preserve_enrollment_state: true          # Maintain enrollment status across simulation years
    cross_year_eligibility_tracking: true   # Track eligibility changes across years
    enrollment_anniversary_processing: true # Process enrollment anniversaries
    re_enrollment_after_termination: true   # Handle re-enrollment for rehires

  # Performance and optimization settings
  performance:
    batch_processing_size: 10000    # Process enrollment in batches for large populations
    enable_parallel_processing: true # Enable parallel processing for performance
    cache_demographic_calculations: true # Cache demographic-based probability calculations
    materialization_strategy: "incremental" # dbt materialization strategy for enrollment models

employee_id_generation:
  baseline_format: "hybrid"  # Options: "legacy" (EMP_NNNNNN), "hybrid" (EMP_YYYY_NNNNNN), "unified" (EMP_YYYY_XXXXXXXX_NNNNNN)
  new_hire_format: "hash_based"  # Options: "hash_based" (NH_YYYY_XXXXXXXX_NNNNNN), "simple" (NH_YYYY_NNNNNN)
  enable_cross_validation: true  # Validate uniqueness across baseline and new hire IDs
  migration_mode: false  # Support for transitioning from legacy formats
  batch_generation: true  # Use batch generation for performance optimization

# Employer match configuration
employer_match:
  # Active match formula selection
  active_formula: 'simple_match'  # Options: 'simple_match', 'tiered_match', 'stretch_match'

  # Epic E058: Employer match eligibility configuration
  apply_eligibility: false  # Backward compatibility toggle (default: false for Phase 1)

  # Match eligibility requirements (independent from core eligibility)
  eligibility:
    minimum_tenure_years: 0        # Minimum years of service (default: 0 for immediate match eligibility)
    require_active_at_year_end: true  # Must be active on Dec 31 (default: true)
    minimum_hours_annual: 1000     # Minimum hours worked (default: 1000)
    allow_new_hires: true          # Allow new hires to qualify (tenure exception)
    allow_terminated_new_hires: false  # Allow new-hire terminations to qualify when enabled
    allow_experienced_terminations: false  # Allow experienced terminations to qualify when enabled

  # Match formula definitions
  formulas:
    simple_match:
      name: 'Simple Match'
      type: 'simple'
      match_rate: 0.50  # 50% match on all deferrals
      max_match_percentage: 0.06  # Cap at 3% of compensation

    tiered_match:
      name: 'Tiered Match'
      type: 'tiered'
      tiers:
        - tier: 1
          employee_min: 0.00
          employee_max: 0.03
          match_rate: 1.00    # 100% match on first 3%
        - tier: 2
          employee_min: 0.03
          employee_max: 0.05
          match_rate: 0.50    # 50% match on next 2%
      max_match_percentage: 0.04  # Cap at 4% of compensation

    stretch_match:
      name: 'Stretch Match (Encourages Higher Deferrals)'
      type: 'tiered'
      tiers:
        - tier: 1
          employee_min: 0.00
          employee_max: 0.12
          match_rate: 0.25     # 25% match on first 12%
      max_match_percentage: 0.03  # Cap at 3% of compensation

    # Alternative tiered formula (for testing)
    enhanced_tiered:
      name: 'Enhanced Tiered Match'
      type: 'tiered'
      tiers:
        - tier: 1
          employee_min: 0.00
          employee_max: 0.03
          match_rate: 1.00    # 100% on first 3%
        - tier: 2
          employee_min: 0.03
          employee_max: 0.05
          match_rate: 0.50    # 50% on next 2%
      max_match_percentage: 0.04  # Cap at 4% of compensation

# Employer core (non-elective) contribution configuration
employer_core_contribution:
  enabled: true                    # Master on/off switch
  contribution_rate: 0.01         # 2% default core contribution rate

  # Eligibility requirements (dbt variables for int_employer_eligibility.sql)
  eligibility:
    minimum_tenure_years: 0        # Minimum years of service (default: 1 year)
    require_active_at_year_end: true  # Must be active on Dec 31 (default: true)
    minimum_hours_annual: 1000     # Minimum hours worked (default: 1000)
    allow_new_hires: true          # Allow new hires to qualify (tenure exception)
    allow_terminated_new_hires: false  # Allow new-hire terminations to qualify when enabled
    allow_experienced_terminations: false  # Allow experienced terminations to qualify when enabled

# Multi-year simulation configuration
multi_year:
  # Optimization settings
  optimization:
    level: "high"  # Options: "high", "medium", "low", "fallback"
    max_workers: 4  # Maximum concurrent workers for parallel processing
    batch_size: 1000  # Processing batch size
    memory_limit_gb: 8.0  # Memory limit in GB (null for no limit)

  # Performance tuning
  performance:
    enable_state_compression: true  # Compress simulation state between years
    enable_concurrent_processing: true  # Enable concurrent year processing
    enable_parallel_dbt: true  # Enable parallel dbt model execution
    cache_workforce_snapshots: true  # Cache workforce snapshots for performance

  # State management
  state:
    enable_checkpointing: true  # Enable simulation checkpointing for resume
    checkpoint_frequency: 1  # Checkpoint every N years
    preserve_intermediate_states: false  # Keep intermediate year states
    compression_level: 6  # State compression level (1-9)

  # Resume and error handling
  resume:
    enable_resume: true  # Allow resuming from checkpoints
    auto_resume_on_failure: false  # Automatically resume from last checkpoint
    cleanup_on_success: true  # Clean up intermediate files on successful completion

  # Error handling
  error_handling:
    fail_fast: false  # Stop on first error vs continue processing other years
    max_retries: 3  # Maximum retry attempts per year
    retry_delay_seconds: 5  # Delay between retries
    validation_mode: "strict"  # Options: "strict", "warnings", "disabled"

  # Transition strategy
  transition:
    strategy: "optimized"  # Options: "optimized", "conservative", "parallel"
    batch_workforce_updates: true  # Batch workforce state transitions
    optimize_event_processing: true  # Optimize event generation and processing

  # Monitoring and logging
  monitoring:
    enable_performance_monitoring: true  # Track performance metrics
    enable_progress_reporting: true  # Report progress during execution
    log_level: "INFO"  # Logging level for multi-year operations
    enable_memory_profiling: false  # Enable memory usage profiling

# Epic E035: Automatic Annual Deferral Rate Escalation Configuration (Simplified)
deferral_auto_escalation:
  enabled: false                 # Master on/off switch
  effective_day: "01-01"        # MM-DD for escalation effective date
  increment_amount: 0.01        # Annual escalation rate (default 1%)
  maximum_rate: 0.10            # Cap for deferral rate (default 10%)
  hire_date_cutoff: "2999-01-01"        # Optional YYYY-MM-DD; only employees hired on/before this date are eligible
  require_active_enrollment: true  # Only escalate enrolled participants

# Deferral baseline behavior (Option A default)
deferral_baseline:
  mode: "frozen"   # "frozen" (default) or "evented" (future)

# Epic E049: Census Deferral Rate Integration Configuration
deferral_rates:
  use_census_rates: true              # Use actual census deferral rates instead of hard-coded defaults
  census_rate_field: "employee_deferral_rate"  # Field in census data containing deferral rates
  pre_enrolled_fallback: 0.03         # Fallback rate for pre-enrolled employees with missing/invalid rates
  plan_deferral_cap: 0.75             # Maximum deferral rate (75% IRS limit)
  normalize_percentages: true         # Automatically convert percentages to decimals (7.5 -> 0.075)
  generate_synthetic_events: true     # Create synthetic enrollment events for census pre-enrolled participants

# Dagster op configuration (maintained for backward compatibility)
ops:
  run_multi_year_simulation:
    config:
      start_year: 2025
      end_year: 2029
      target_growth_rate: 0.03
      total_termination_rate: 0.12
      new_hire_termination_rate: 0.25
      random_seed: 42
      full_refresh: false
