# PlanWise Navigator Configuration with Advanced Resource Management
# Story S067-03: Advanced Memory Management & Optimization Example

# Core simulation settings
simulation:
  start_year: 2025
  end_year: 2027
  random_seed: 42
  target_growth_rate: 0.03

# Compensation parameters
compensation:
  cola_rate: 0.005
  merit_budget: 0.025
  promotion_compensation:
    base_increase_pct: 0.20
    distribution_range: 0.05
    max_cap_pct: 0.30
    max_cap_amount: 500000
    distribution_type: "uniform"

# Workforce modeling
workforce:
  total_termination_rate: 0.12
  new_hire_termination_rate: 0.25

# Enterprise identifiers
scenario_id: "resource_mgmt_demo"
plan_design_id: "advanced_401k"

# Enrollment settings
enrollment:
  auto_enrollment:
    enabled: true
    scope: "all_eligible_employees"
    window_days: 45
    default_deferral_rate: 0.06
    opt_out_grace_period: 30
    opt_out_rates:
      by_age:
        young: 0.10
        mid_career: 0.07
        mature: 0.05
        senior: 0.03
      by_income:
        low_income: 1.20
        moderate: 1.00
        high: 0.70
        executive: 0.50

# Plan eligibility
eligibility:
  waiting_period_days: null

plan_eligibility:
  minimum_age: null

# Advanced orchestration configuration with resource management
orchestrator:
  threading:
    enabled: true
    thread_count: 4
    mode: "selective"
    memory_per_thread_gb: 1.5

    # Model-level parallelization
    model_parallelization:
      enabled: true
      max_workers: 4
      memory_limit_mb: 4000.0
      enable_conditional_parallelization: true
      deterministic_execution: true
      resource_monitoring: true

      safety:
        fallback_on_resource_pressure: true
        validate_execution_safety: true
        abort_on_dependency_conflict: true
        max_retries_per_model: 2

    # Advanced Resource Management (Story S067-03)
    resource_management:
      enabled: true

      # Memory monitoring configuration
      memory_monitoring:
        enabled: true
        monitoring_interval_seconds: 1.0
        history_size: 200

        thresholds:
          moderate_mb: 2000.0      # 2GB - moderate pressure
          high_mb: 3000.0          # 3GB - high pressure
          critical_mb: 3500.0      # 3.5GB - critical pressure
          gc_trigger_mb: 2500.0    # 2.5GB - trigger garbage collection
          fallback_trigger_mb: 3200.0  # 3.2GB - trigger fallback mode

        auto_gc_enabled: true
        fallback_enabled: true
        profiling_enabled: false

        # Memory leak detection
        leak_detection_enabled: true
        leak_threshold_mb: 800.0
        leak_window_minutes: 15

        # Recommendation engine
        recommendation_window_minutes: 5
        min_samples_for_recommendation: 10

      # CPU monitoring configuration
      cpu_monitoring:
        enabled: true
        monitoring_interval_seconds: 1.0
        history_size: 200

        thresholds:
          moderate_percent: 70.0    # 70% - moderate CPU usage
          high_percent: 85.0        # 85% - high CPU usage
          critical_percent: 95.0    # 95% - critical CPU usage

      # Adaptive thread scaling
      adaptive_scaling_enabled: true
      min_threads: 1
      max_threads: 8
      adjustment_cooldown_seconds: 30.0

      # Performance benchmarking (optional)
      benchmarking_enabled: false
      benchmark_thread_counts: [1, 2, 4, 6, 8]

      # Resource cleanup
      auto_cleanup_enabled: true
      cleanup_threshold_mb: 2500.0

# Performance optimization
optimization:
  level: "high"
  max_workers: 4
  batch_size: 1000
  memory_limit_gb: 4.0

  # Adaptive memory management (legacy - kept for compatibility)
  adaptive_memory:
    enabled: true
    monitoring_interval_seconds: 2.0
    history_size: 100

    thresholds:
      moderate_mb: 2000.0
      high_mb: 3000.0
      critical_mb: 3500.0
      gc_trigger_mb: 2500.0
      fallback_trigger_mb: 3200.0

    batch_sizes:
      low: 250
      medium: 500
      high: 1000
      fallback: 100
