# Asset-level configuration (used by simulation_config asset)
simulation:
  start_year: 2025
  end_year: 2029
  random_seed: 42
  target_growth_rate: 0.03

workforce:
  total_termination_rate: 0.12
  new_hire_termination_rate: 0.25

compensation:
  cola_rate: 0.01
  merit_budget: 0.035
  growth_target: 0.02
  growth_tolerance: 0.005
  calculation_methodology: "full_year_equivalent"  # options: current, continuous, full_year_equivalent

plan_year:
  start_date: "2024-01-01"  # Plan year start date for compensation calculations
  end_date: "2024-12-31"    # Plan year end date for compensation calculations
  annualization_method: "calendar_days"  # Method for annualizing partial year compensation (calendar_days vs work_days)

# Dagster op configuration
ops:
  run_multi_year_simulation:
    config:
      start_year: 2025
      end_year: 2029
      target_growth_rate: 0.03
      total_termination_rate: 0.12
      new_hire_termination_rate: 0.25
      random_seed: 42
      full_refresh: false
