ops:
  run_multi_year_simulation:
    config:
      start_year: 2025
      end_year: 2029
      target_growth_rate: 0.03
      total_termination_rate: 0.12
      new_hire_termination_rate: 0.25
      random_seed: 42
