version: 2

# MIGRATION NOTICE:
# The following models have been converted to dbt tests in dbt/tests/data_quality/
# - dq_duplicate_events_detection -> test_duplicate_events.sql
# - dq_compensation_bounds_check -> test_compensation_bounds.sql
# - dq_integrity_violations -> test_integrity_violations.sql
# - dq_deferral_rate_validation -> test_deferral_rate_validation.sql
#
# To run these validations, use:
#   dbt test --select tag:data_quality
