version: 2

models:
  - name: stg_census_data
    description: >
      LOCKED CONTRACT: Primary census data foundation model.

      This model serves as the foundation for all workforce simulation and must maintain
      schema stability. Changes to this contract require architecture review as it
      affects all downstream models in the simulation pipeline.
    config:
      tags: ["foundation", "locked", "contract"]
    columns:
      - name: employee_id
        description: "PRIMARY KEY - Unique identifier for each employee. NEVER change this field."
        data_type: varchar
        constraints:
          - type: not_null
          - type: unique
        data_tests:
          - unique
          - not_null
      - name: employee_ssn
        description: "Social Security Number for compliance and reporting. Required for audit trails."
        data_type: varchar
        constraints:
          - type: not_null
        data_tests:
          - not_null
      - name: employee_birth_date
        description: "Employee birth date for age calculations in simulation models."
        data_type: date
        constraints:
          - type: not_null
      - name: employee_hire_date
        description: "Employee hire date for tenure calculations and baseline establishment."
        data_type: date
        constraints:
          - type: not_null
      - name: employee_termination_date
        description: "Termination date if applicable. NULL for active employees."
        data_type: date
      - name: employee_gross_compensation
        description: "Gross annual compensation used for level assignment and simulation baseline."
        data_type: double
        constraints:
          - type: not_null
      - name: active
        description: "Active status flag from source system."
        data_type: boolean
      - name: employee_plan_year_compensation
        description: "Plan year compensation (may be partial year)."
        data_type: double
        constraints:
          - type: not_null
      - name: employee_annualized_compensation
        description: "Annualized compensation calculated for partial year workers."
        data_type: double
        constraints:
          - type: not_null
      - name: employee_capped_compensation
        description: "Capped compensation for benefit calculations."
        data_type: decimal(12,2)
      - name: employee_deferral_rate
        description: "Employee deferral rate for benefit modeling."
        data_type: decimal(7,5)
      - name: employee_contribution
        description: "Employee contribution amount."
        data_type: decimal(12,2)
      - name: pre_tax_contribution
        description: "Employee pre-tax contribution amount."
        data_type: decimal(12,2)
      - name: roth_contribution
        description: "Employee Roth contribution amount."
        data_type: decimal(12,2)
      - name: after_tax_contribution
        description: "Employee after-tax contribution amount."
        data_type: decimal(12,2)
      - name: employer_core_contribution
        description: "Employer core contribution amount."
        data_type: decimal(12,2)
      - name: employer_match_contribution
        description: "Employer match contribution amount."
        data_type: decimal(12,2)
      - name: eligibility_entry_date
        description: "Benefit eligibility entry date."
        data_type: date
        constraints:
          - type: not_null
      - name: employee_eligibility_date
        description: "Date when employee becomes eligible for DC plan participation (hire date + waiting period)."
        data_type: date
        constraints:
          - type: not_null
        data_tests:
          - not_null
      - name: waiting_period_days
        description: "Number of days employee must wait after hire to become eligible for DC plan participation."
        data_type: integer
        constraints:
          - type: not_null
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 365
      - name: current_eligibility_status
        description: "Current eligibility status based on eligibility date vs census year end (eligible/pending)."
        data_type: varchar
        constraints:
          - type: not_null
        data_tests:
          - not_null
          - accepted_values:
              values: ['eligible', 'pending']
      - name: employee_enrollment_date
        description: "Date when employee enrolled in DC plan. Set to census year end only if employee_deferral_rate > 0."
        data_type: date

  - name: stg_census_duplicates_audit
    description: >
      Audit table tracking duplicate employee_ids found in raw census data.
      Used for data quality monitoring and source system debugging.
    columns:
      - name: employee_id
        description: Employee identifier (may have duplicates in this audit table)
        data_tests:
          - not_null
      - name: duplicate_count
        description: Total number of times this employee_id appears in raw data
        data_tests:
          - not_null
      - name: occurrence_rank
        description: Rank of this occurrence (1 = kept, >1 = dropped)
        data_tests:
          - not_null
      - name: dedup_status
        description: Whether this record was KEPT or DROPPED during deduplication
        data_tests:
          - not_null
          - accepted_values:
              values: ['KEPT', 'DROPPED']
      - name: audit_timestamp
        description: Timestamp when this audit record was created
        data_tests:
          - not_null

  - name: stg_config_job_levels
    description: >
      Job levels configuration with compensation bands and career progression parameters.
      Includes promotion probabilities and merit increase rates by level.
    columns:
      - name: level_id
        description: Unique identifier for job level
        data_tests:
          - unique
          - not_null
      - name: level_name
        description: Display name for the job level
        data_tests:
          - not_null
      - name: min_compensation
        description: Minimum compensation for this level
        data_tests:
          - not_null
      - name: max_compensation
        description: Maximum compensation for this level
      - name: avg_annual_merit_increase
        description: Average annual merit increase rate for this level
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 0.2
      - name: promotion_probability
        description: Annual probability of promotion from this level
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

  - name: stg_config_cola_by_year
    description: >
      Cost of Living Adjustment rates by simulation year.
      Used for annual compensation adjustments.
    columns:
      - name: year
        description: Simulation year
        data_tests:
          - unique
          - not_null
      - name: cola_rate
        description: COLA rate for the year
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: -0.1
              max_value: 0.1

  - name: stg_config_termination_hazard_base
    description: Base termination hazard rate configuration
    columns:
      - name: base_rate_for_new_hire
        description: Base termination rate for new hires
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

  - name: stg_config_termination_hazard_age_multipliers
    description: Age-based multipliers for termination hazard rates
    columns:
      - name: age_band
        description: Age band category
        data_tests:
          - unique
          - not_null
      - name: multiplier
        description: Multiplier for the age band
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5

  - name: stg_config_termination_hazard_tenure_multipliers
    description: Tenure-based multipliers for termination hazard rates
    columns:
      - name: tenure_band
        description: Tenure band category
        data_tests:
          - unique
          - not_null
      - name: multiplier
        description: Multiplier for the tenure band
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5

  - name: stg_config_promotion_hazard_base
    description: Base promotion hazard rate configuration
    columns:
      - name: base_rate
        description: Base promotion rate
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
      - name: level_dampener_factor
        description: Factor to reduce promotion probability at higher levels
        data_tests:
          - not_null

  - name: stg_config_promotion_hazard_age_multipliers
    description: Age-based multipliers for promotion hazard rates
    columns:
      - name: age_band
        description: Age band category
        data_tests:
          - unique
          - not_null
      - name: multiplier
        description: Multiplier for the age band
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5

  - name: stg_config_promotion_hazard_tenure_multipliers
    description: Tenure-based multipliers for promotion hazard rates
    columns:
      - name: tenure_band
        description: Tenure band category
        data_tests:
          - unique
          - not_null
      - name: multiplier
        description: Multiplier for the tenure band
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5

  - name: stg_config_raises_hazard
    description: Merit raises hazard configuration
    columns:
      - name: merit_base
        description: Base merit raise rate
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 0.2

  - name: stg_comp_levers
    description: >
      Compensation parameter levers for dynamic scenario-based modeling.
      Enables analysts to adjust compensation parameters without code changes.
    config:
      tags: ["critical", "locked"]
    columns:
      - name: scenario_id
        description: Unique identifier for the parameter scenario
        data_tests:
          - not_null
      - name: fiscal_year
        description: Fiscal year for which these parameters apply
        data_tests:
          - not_null
      - name: job_level
        description: Job level (1-5) for which these parameters apply
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
      - name: event_type
        description: Type of workforce event (RAISE, PROMOTION, etc.)
        data_tests:
          - not_null
          - accepted_values:
              values: ['RAISE', 'PROMOTION', 'TERMINATION', 'HIRE']
      - name: parameter_name
        description: Name of the parameter being configured
        data_tests:
          - not_null
      - name: parameter_value
        description: Value of the parameter
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10  # Allow values > 1 for salary adjustments and multipliers
      - name: is_locked
        description: Whether this parameter is locked from further changes
        data_tests:
          - not_null

  - name: stg_comp_targets
    description: >
      Compensation and workforce targets for scenario optimization.
      Defines target metrics and acceptable tolerance ranges.
    columns:
      - name: scenario_id
        description: Unique identifier for the target scenario
        data_tests:
          - not_null
      - name: fiscal_year
        description: Fiscal year for which these targets apply
        data_tests:
          - not_null
      - name: metric_name
        description: Name of the target metric
        data_tests:
          - not_null
      - name: target_value
        description: Target value for the metric
        data_tests:
          - not_null
      - name: tolerance_pct
        description: Acceptable percentage tolerance around the target
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
      - name: priority
        description: Priority level for optimization (high, medium, low)
        data_tests:
          - not_null
          - accepted_values:
              values: ['high', 'medium', 'low']

  - name: stg_scenario_meta
    description: >
      Metadata for parameter scenarios including creation tracking and status.
      Supports scenario management and audit trail.
    columns:
      - name: scenario_id
        description: Unique identifier for the scenario
        data_tests:
          - unique
          - not_null
      - name: scenario_name
        description: Human-readable name for the scenario
        data_tests:
          - not_null
      - name: status
        description: Current status of the scenario
        data_tests:
          - not_null
          - accepted_values:
              values: ['draft', 'published', 'archived']
      - name: created_by
        description: User who created the scenario
        data_tests:
          - not_null
