"""Pydantic models for net employer cost (issue #444).

Gross employer cost (match + core) is what the Cost Comparison page has always
shown. These models add the forfeiture offset and the resulting *net* cost — the
number a plan sponsor actually asks for — along with the flags that keep it
honest: whether the offset could be measured at all, and whether the selected
forfeiture policy reduces employer outlay in the first place.
"""

from __future__ import annotations

from decimal import Decimal
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_serializer


class ForfeiturePolicy(str, Enum):
    """What the plan does with forfeited employer money.

    These are not three flavours of the same subtraction. Only the first two
    reduce the sponsor's outlay; reallocation moves the money to remaining
    participants' accounts and the sponsor still funds the full match.
    """

    OFFSET_EMPLOYER_CONTRIBUTIONS = "offset_employer_contributions"
    PAY_PLAN_EXPENSES = "pay_plan_expenses"
    REALLOCATE_TO_PARTICIPANTS = "reallocate_to_participants"


#: Whether a policy reduces employer cost. Reallocation does not.
POLICY_REDUCES_EMPLOYER_COST: dict[ForfeiturePolicy, bool] = {
    ForfeiturePolicy.OFFSET_EMPLOYER_CONTRIBUTIONS: True,
    ForfeiturePolicy.PAY_PLAN_EXPENSES: True,
    ForfeiturePolicy.REALLOCATE_TO_PARTICIPANTS: False,
}


#: One-line descriptions used by the methodology copy on every surface.
POLICY_DESCRIPTIONS: dict[ForfeiturePolicy, str] = {
    ForfeiturePolicy.OFFSET_EMPLOYER_CONTRIBUTIONS: (
        "Forfeitures are applied against the next plan year's employer "
        "contributions, reducing the sponsor's outlay."
    ),
    ForfeiturePolicy.PAY_PLAN_EXPENSES: (
        "Forfeitures pay plan expenses the sponsor would otherwise fund in "
        "cash, reducing the sponsor's outlay."
    ),
    ForfeiturePolicy.REALLOCATE_TO_PARTICIPANTS: (
        "Forfeitures are reallocated to remaining participants' accounts. The "
        "sponsor still funds the full match, so employer cost is not reduced."
    ),
}


class EmployerCostOffsetRow(BaseModel):
    """The forfeiture offset applied to one simulation year's employer cost.

    Forfeitures generated by year N terminations are recognized and applied in
    year N + 1, so ``source_year`` is always ``simulation_year - 1``.
    """

    simulation_year: int = Field(
        ..., description="The year whose employer cost this offset applies to"
    )
    source_year: Optional[int] = Field(
        None,
        description=(
            "The termination year that generated the forfeitures, or null when "
            "no prior year exists in the simulation horizon"
        ),
    )
    forfeitures_generated: Optional[Decimal] = Field(
        None,
        description=(
            "Forfeitures generated in source_year, disclosed regardless of "
            "policy. Null when no measurable basis exists — never a silent $0."
        ),
    )
    offset_amount: Optional[Decimal] = Field(
        None,
        description=(
            "The amount actually subtracted from employer cost. $0 under "
            "reallocate_to_participants; null when no measurable basis exists."
        ),
    )
    participant_allocation: Optional[Decimal] = Field(
        None,
        description=(
            "Forfeitures allocated to remaining participants rather than the "
            "sponsor. Non-zero only under reallocate_to_participants."
        ),
    )
    basis_available: bool = Field(
        ...,
        description=(
            "False when the offset could not be measured. Render the year as "
            "gross-only and flagged, never as a $0 offset."
        ),
    )
    unavailable_reason: Optional[str] = Field(
        None, description="Why basis_available is false, for display"
    )

    @field_serializer(
        "forfeitures_generated",
        "offset_amount",
        "participant_allocation",
    )
    def serialize_decimal(self, v: Optional[Decimal]) -> Optional[float]:
        """Serialize Decimal as float for JSON responses."""
        return None if v is None else float(v)


class EmployerCostYear(BaseModel):
    """Gross, offset and net employer cost for one simulation year."""

    simulation_year: int
    gross_employer_match: Decimal = Field(..., ge=0)
    gross_employer_core: Decimal = Field(..., ge=0)
    gross_employer_cost: Decimal = Field(..., ge=0)
    total_compensation: Decimal = Field(
        ...,
        ge=0,
        description=(
            "Sum of prorated annual compensation across the snapshot "
            "population. Not an IRC-eligibility-filtered figure."
        ),
    )
    forfeitures_generated: Optional[Decimal] = Field(
        None, description="Forfeitures recognized for this year (from year - 1)"
    )
    forfeiture_offset_applied: Optional[Decimal] = Field(
        None, description="Policy-dependent reduction to employer cost"
    )
    net_employer_cost: Optional[Decimal] = Field(
        None,
        description=(
            "Gross cost minus the applied offset. Null when the offset has no "
            "measurable basis; show gross only, flagged."
        ),
    )
    offset_basis_available: bool
    offset_unavailable_reason: Optional[str] = None
    gross_cost_pct_of_compensation: Decimal = Field(..., ge=0)
    net_cost_pct_of_compensation: Optional[Decimal] = None

    @field_serializer(
        "gross_employer_match",
        "gross_employer_core",
        "gross_employer_cost",
        "total_compensation",
        "forfeitures_generated",
        "forfeiture_offset_applied",
        "net_employer_cost",
        "gross_cost_pct_of_compensation",
        "net_cost_pct_of_compensation",
    )
    def serialize_decimal(self, v: Optional[Decimal]) -> Optional[float]:
        """Serialize Decimal as float for JSON responses."""
        return None if v is None else float(v)


class EmployerCostSeries(BaseModel):
    """One scenario's gross/offset/net employer cost across the horizon."""

    scenario_id: str
    scenario_name: str
    forfeiture_policy: ForfeiturePolicy
    schedule_name: str
    years: List[EmployerCostYear]
    total_gross_employer_cost: Decimal = Field(..., ge=0)
    total_forfeiture_offset: Decimal = Field(
        ...,
        ge=0,
        description="Sum of measurable offsets only; unmeasurable years excluded",
    )
    total_net_employer_cost: Decimal = Field(
        ...,
        description=(
            "Gross total minus measurable offsets. Years without a measurable "
            "offset contribute their gross cost unchanged; see "
            "years_without_offset_basis."
        ),
    )
    years_without_offset_basis: List[int] = Field(
        default_factory=list,
        description="Years whose gross cost is included with no offset applied",
    )

    @field_serializer(
        "total_gross_employer_cost",
        "total_forfeiture_offset",
        "total_net_employer_cost",
    )
    def serialize_decimal(self, v: Decimal) -> float:
        """Serialize Decimal as float for JSON responses."""
        return float(v)
